apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/htcondor-setup
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/htcondor-setup
    actuationTool:
      flavor: Terraform
      version: ">= 0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which HTCondor pool will be created
        varType: string
        required: true
      - name: deployment_name
        description: Cluster Toolkit deployment name. HTCondor cloud resource names will include this value.
        varType: string
        required: true
      - name: labels
        description: Labels to add to resources. List key, value pairs.
        varType: map(string)
        required: true
      - name: region
        description: Default region for creating resources
        varType: string
        required: true
      - name: subnetwork_self_link
        description: The self link of the subnetwork in which Central Managers will be placed.
        varType: string
        required: true
      - name: access_point_service_account_email
        description: Service account e-mail for HTCondor Access Point
        varType: string
        required: true
      - name: central_manager_service_account_email
        description: Service account e-mail for HTCondor Central Manager
        varType: string
        required: true
      - name: execute_point_service_account_email
        description: Service account e-mail for HTCondor Execute Points
        varType: string
        required: true
    outputs:
      - name: htcondor_bucket_name
        description: Name of the HTCondor configuration bucket
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
