apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/pbspro-install
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/pbspro-install
    actuationTool:
      flavor: Terraform
      version: ">= 0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: rpm_url
        description: Path to PBS Pro RPM file for select PBS host type (server, client, execution)
        varType: string
        required: true
      - name: pbs_exec
        description: Root path in which to install PBS
        varType: string
        defaultValue: /opt/pbs
      - name: pbs_data_service_user
        description: PBS Data Service POSIX user
        varType: string
        defaultValue: pbsdata
      - name: pbs_home
        description: PBS working directory
        varType: string
        defaultValue: /var/spool/pbs
      - name: pbs_license_server
        description: IP address or DNS name of PBS license server (required only for PBS server hosts)
        varType: string
        defaultValue: CHANGE_THIS_TO_PBS_PRO_LICENSE_SERVER_HOSTNAME
      - name: pbs_license_server_port
        description: Networking port of PBS license server
        varType: number
        defaultValue: 6200
      - name: pbs_server
        description: IP address or DNS name of PBS server host (required only for PBS client and execution hosts)
        varType: string
        defaultValue: CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME
      - name: pbs_role
        description: "Type of PBS host to provision: server, client, execution"
        varType: string
        required: true
    outputs:
      - name: runner
        description: Toolkit runner to install the select PBS Pro host
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
