apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/schedmd-slurm-gcp-v-6-login
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/schedmd-slurm-gcp-v6-login
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project ID to create resources in.
        varType: string
        required: true
      - name: region
        description: Region where the instances should be created.
        varType: string
      - name: zone
        description: |
          Zone where the instances should be created. If not specified, instances will be
          spread across available zones in the region.
        varType: string
      - name: name_prefix
        description: |
          Unique name prefix for login nodes. Automatically populated by the module id if not set.
          If setting manually, ensure a unique value across all login groups.
        varType: string
        required: true
      - name: num_instances
        description: Number of instances to create. This value is ignored if static_ips is provided.
        varType: number
        defaultValue: 1
      - name: disk_type
        description: Boot disk type, can be either hyperdisk-balanced, pd-ssd, pd-standard, pd-balanced, or pd-extreme.
        varType: string
        defaultValue: pd-ssd
      - name: disk_size_gb
        description: Boot disk size in GB.
        varType: number
        defaultValue: 50
      - name: disk_auto_delete
        description: Whether or not the boot disk should be auto-deleted.
        varType: bool
        defaultValue: true
      - name: disk_labels
        description: Labels specific to the boot disk. These will be merged with var.labels.
        varType: map(string)
        defaultValue: {}
      - name: additional_disks
        description: List of maps of disks.
        varType: |-
          list(object({
              disk_name    = string
              device_name  = string
              disk_type    = string
              disk_size_gb = number
              disk_labels  = map(string)
              auto_delete  = bool
              boot         = bool
            }))
        defaultValue: []
      - name: additional_networks
        description: Additional network interface details for GCE, if any.
        varType: |-
          list(object({
              access_config = optional(list(object({
                nat_ip       = string
                network_tier = string
              })), [])
              alias_ip_range = optional(list(object({
                ip_cidr_range         = string
                subnetwork_range_name = string
              })), [])
              ipv6_access_config = optional(list(object({
                network_tier = string
              })), [])
              network            = optional(string)
              network_ip         = optional(string, "")
              nic_type           = optional(string)
              queue_count        = optional(number)
              stack_type         = optional(string)
              subnetwork         = optional(string)
              subnetwork_project = optional(string)
            }))
        defaultValue: []
      - name: enable_smt
        description: Enables Simultaneous Multi-Threading (SMT) on instance.
        varType: bool
        defaultValue: false
      - name: disable_smt
        description: "DEPRECATED: Use `enable_smt` instead."
        varType: bool
      - name: static_ips
        description: List of static IPs for VM instances.
        varType: list(string)
        defaultValue: []
      - name: bandwidth_tier
        description: "  Configures the network interface card and the maximum egress bandwidth for VMs.\n  - Setting `platform_default` respects the Google Cloud Platform API default values for networking.\n  - Setting `virtio_enabled` explicitly selects the VirtioNet network adapter.\n  - Setting `gvnic_enabled` selects the gVNIC network adapter (without Tier 1 high bandwidth).\n  - Setting `tier_1_enabled` selects both the gVNIC adapter and Tier 1 high bandwidth networking.\n  - Note: both gVNIC and Tier 1 networking require a VM image with gVNIC support as well as specific VM families and shapes.\n  - See [official docs](https://cloud.google.com/compute/docs/networking/configure-vm-with-high-bandwidth-configuration) for more details.\n"
        varType: string
        defaultValue: platform_default
      - name: can_ip_forward
        description: Enable IP forwarding, for NAT instances for example.
        varType: bool
        defaultValue: false
      - name: enable_login_public_ips
        description: If set to true. The login node will have a random public IP assigned to it.
        varType: bool
        defaultValue: false
      - name: disable_login_public_ips
        description: "DEPRECATED: Use `enable_login_public_ips` instead."
        varType: bool
      - name: enable_oslogin
        description: |
          Enables Google Cloud os-login for user login and authentication for VMs.
          See https://cloud.google.com/compute/docs/oslogin
        varType: bool
        defaultValue: true
      - name: enable_confidential_vm
        description: "Enable the Confidential VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: enable_shielded_vm
        description: "Enable the Shielded VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: shielded_instance_config
        description: |
          Shielded VM configuration for the instance. Note: not used unless
          enable_shielded_vm is 'true'.
            enable_integrity_monitoring : Compare the most recent boot measurements to the
            integrity policy baseline and return a pair of pass/fail results depending on
            whether they match or not.
            enable_secure_boot : Verify the digital signature of all boot components, and
            halt the boot process if signature verification fails.
            enable_vtpm : Use a virtualized trusted platform module, which is a
            specialized computer chip you can use to encrypt objects like keys and
            certificates.
        varType: |-
          object({
              enable_integrity_monitoring = bool
              enable_secure_boot          = bool
              enable_vtpm                 = bool
            })
        defaultValue:
          enable_integrity_monitoring: true
          enable_secure_boot: true
          enable_vtpm: true
      - name: guest_accelerator
        description: List of the type and count of accelerator cards attached to the instance.
        varType: |-
          list(object({
              type  = string,
              count = number
            }))
        defaultValue: []
      - name: labels
        description: Labels, provided as a map.
        varType: map(string)
        defaultValue: {}
      - name: machine_type
        description: Machine type to create.
        varType: string
        defaultValue: c2-standard-4
      - name: metadata
        description: Metadata, provided as a map.
        varType: map(string)
        defaultValue: {}
      - name: min_cpu_platform
        description: |
          Specifies a minimum CPU platform. Applicable values are the friendly names of
          CPU platforms, such as Intel Haswell or Intel Skylake. See the complete list:
          https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform
        varType: string
      - name: preemptible
        description: Allow the instance to be preempted.
        varType: bool
        defaultValue: false
      - name: on_host_maintenance
        description: Instance availability Policy.
        varType: string
        defaultValue: MIGRATE
      - name: service_account_email
        description: Service account e-mail address to attach to the login instances.
        varType: string
      - name: service_account_scopes
        description: Scopes to attach to the login instances.
        varType: set(string)
        defaultValue:
          - https://www.googleapis.com/auth/cloud-platform
      - name: service_account
        description: "DEPRECATED: Use `service_account_email` and `service_account_scopes` instead."
        varType: |-
          object({
              email  = string
              scopes = set(string)
            })
      - name: instance_template
        description: "DEPRECATED: Instance template can not be specified for login nodes."
        varType: string
      - name: instance_image
        description: |
          Defines the image that will be used in the Slurm controller VM instance.

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.

          For more information on creating custom images that comply with Slurm on GCP
          see the "Slurm on GCP Custom Images" section in docs/vm-images.md.
        varType: map(string)
        defaultValue:
          family: slurm-gcp-6-8-hpc-rocky-linux-8
          project: schedmd-slurm-public
      - name: instance_image_custom
        description: |
          A flag that designates that the user is aware that they are requesting
          to use a custom and potentially incompatible image for this Slurm on
          GCP module.

          If the field is set to false, only the compatible families and project
          names will be accepted.  The deployment will fail with any other image
          family or name.  If set to true, no checks will be done.

          See: https://goo.gle/hpc-slurm-images
        varType: bool
        defaultValue: false
      - name: allow_automatic_updates
        description: |
          If false, disables automatic system package updates on the created instances.  This feature is
          only available on supported images (or images derived from them).  For more details, see
          https://cloud.google.com/compute/docs/instances/create-hpc-vm#disable_automatic_updates
        varType: bool
        defaultValue: true
      - name: tags
        description: Network tag list.
        varType: list(string)
        defaultValue: []
      - name: subnetwork_self_link
        description: Subnet to deploy to.
        varType: string
        required: true
    outputs:
      - name: login_nodes
        description: Slurm login instance definition.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
