apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/scheduler/batch-login-node
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/scheduler/batch-login-node
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: deployment_name
        description: Name of the deployment, also used for the job_id
        varType: string
        required: true
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: region
        description: The region in which to create the login node
        varType: string
        required: true
      - name: zone
        description: The zone in which to create the login node
        varType: string
        required: true
      - name: labels
        description: Labels to add to the login node. Key-value pairs
        varType: map(string)
        required: true
      - name: instance_template
        description: |
          Login VM instance template self-link. Typically supplied by a
          batch-job-template module. If multiple batch-job-template modules supply the
          instance_template, the first will be used.
        varType: string
        required: true
      - name: network_storage
        description: An array of network attached storage mounts to be configured. Typically supplied by a batch-job-template module.
        varType: |-
          list(object({
              server_ip             = string
              remote_mount          = string
              local_mount           = string
              fs_type               = string
              mount_options         = string
              client_install_runner = map(string)
              mount_runner          = map(string)
            }))
        defaultValue: []
      - name: startup_script
        description: Startup script run before Google Cloud Batch job starts. Typically supplied by a batch-job-template module.
        varType: string
      - name: job_data
        description: List of jobs and supporting data for each, typically provided via "use" from the batch-job-template module.
        varType: |-
          list(object({
              template_contents = string,
              filename          = string,
              id                = string
            }))
        required: true
      - name: job_template_contents
        description: "Deprecated (use `job_data`): The contents of the Google Cloud Batch job template. Typically supplied by a batch-job-template module."
        varType: string
      - name: job_filename
        description: "Deprecated (use `job_data`): The filename of the generated job template file. Typically supplied by a batch-job-template module."
        varType: string
      - name: job_id
        description: "Deprecated (use `job_data`): The ID for the Google Cloud Batch job. Typically supplied by a batch-job-template module for use in the output instructions."
        varType: string
      - name: gcloud_version
        description: |
          The version of the gcloud cli being used. Used for output instructions.
          Valid inputs are `\"alpha\"`, `\"beta\"` and \"\" (empty string for default
          version). Typically supplied by a batch-job-template module. If multiple
          batch-job-template modules supply the gcloud_version, only the first will be used.
        varType: string
        defaultValue: ""
      - name: batch_job_directory
        description: The path of the directory on the login node in which to place the Google Cloud Batch job template
        varType: string
        defaultValue: /home/batch-jobs
      - name: enable_oslogin
        description: Enable or Disable OS Login with "ENABLE" or "DISABLE". Set to "INHERIT" to inherit project OS Login setting.
        varType: string
        defaultValue: ENABLE
    outputs:
      - name: instructions
        description: Instructions for accessing the login node and submitting Google Cloud Batch jobs
      - name: login_node_name
        description: Name of the created VM
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
