apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/schedmd-slurm-gcp-v-5-login
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/schedmd-slurm-gcp-v5-login
    version: 1.41.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.1"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project ID to create resources in.
        varType: string
        required: true
      - name: labels
        description: Labels, provided as a map.
        varType: map(string)
        defaultValue: {}
      - name: disable_smt
        description: Disables Simultaneous Multi-Threading (SMT) on instance.
        varType: bool
        defaultValue: true
      - name: deployment_name
        description: Name of the deployment.
        varType: string
        required: true
      - name: disable_login_public_ips
        description: If set to false. The login will have a random public IP assigned to it. Ignored if access_config is set.
        varType: bool
        defaultValue: true
      - name: slurm_cluster_name
        description: Cluster name, used for resource naming and slurm accounting. If not provided it will default to the first 8 characters of the deployment name (removing any invalid characters).
        varType: string
      - name: controller_instance_id
        description: |
          The server-assigned unique identifier of the controller instance. This value
          must be supplied as an output of the controller module, typically via `use`.
        varType: string
        required: true
      - name: can_ip_forward
        description: Enable IP forwarding, for NAT instances for example.
        varType: bool
        defaultValue: false
      - name: network_self_link
        description: Network to deploy to. Either network_self_link or subnetwork_self_link must be specified.
        varType: string
      - name: subnetwork_self_link
        description: Subnet to deploy to. Either network_self_link or subnetwork_self_link must be specified.
        varType: string
      - name: subnetwork_project
        description: The project that subnetwork belongs to.
        varType: string
      - name: region
        description: |
          Region where the instances should be created.
          Note: region will be ignored if it can be extracted from subnetwork.
        varType: string
      - name: network_ip
        description: "DEPRECATED: Use `static_ips` variable to assign an internal static ip address."
        varType: string
      - name: static_ips
        description: List of static IPs for VM instances.
        varType: list(string)
        defaultValue: []
      - name: access_config
        description: Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet.
        varType: |-
          list(object({
              nat_ip       = string
              network_tier = string
            }))
        defaultValue: []
      - name: zone
        description: |
          Zone where the instances should be created. If not specified, instances will be
          spread across available zones in the region.
        varType: string
      - name: metadata
        description: Metadata, provided as a map.
        varType: map(string)
        defaultValue: {}
      - name: tags
        description: Network tag list.
        varType: list(string)
        defaultValue: []
      - name: machine_type
        description: Machine type to create.
        varType: string
        defaultValue: n2-standard-2
      - name: min_cpu_platform
        description: |
          Specifies a minimum CPU platform. Applicable values are the friendly names of
          CPU platforms, such as Intel Haswell or Intel Skylake. See the complete list:
          https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform
        varType: string
      - name: gpu
        description: "DEPRECATED: use var.guest_accelerator"
        varType: |-
          object({
              type  = string
              count = number
            })
      - name: guest_accelerator
        description: List of the type and count of accelerator cards attached to the instance.
        varType: |-
          list(object({
              type  = string,
              count = number
            }))
        defaultValue: []
      - name: service_account
        description: |
          Service account to attach to the login instance. If not set, the
          default compute service account for the given project will be used with the
          "https://www.googleapis.com/auth/cloud-platform" scope.
        varType: |-
          object({
              email  = string
              scopes = set(string)
            })
      - name: shielded_instance_config
        description: |
          Shielded VM configuration for the instance. Note: not used unless
          enable_shielded_vm is 'true'.
          - enable_integrity_monitoring : Compare the most recent boot measurements to the
            integrity policy baseline and return a pair of pass/fail results depending on
            whether they match or not.
          - enable_secure_boot : Verify the digital signature of all boot components, and
            halt the boot process if signature verification fails.
          - enable_vtpm : Use a virtualized trusted platform module, which is a
            specialized computer chip you can use to encrypt objects like keys and
            certificates.
        varType: |-
          object({
              enable_integrity_monitoring = bool
              enable_secure_boot          = bool
              enable_vtpm                 = bool
            })
        defaultValue:
          enable_integrity_monitoring: true
          enable_secure_boot: true
          enable_vtpm: true
      - name: enable_confidential_vm
        description: "Enable the Confidential VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: enable_shielded_vm
        description: "Enable the Shielded VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: preemptible
        description: Allow the instance to be preempted.
        varType: bool
        defaultValue: false
      - name: on_host_maintenance
        description: Instance availability Policy.
        varType: string
        defaultValue: MIGRATE
      - name: enable_oslogin
        description: |
          Enables Google Cloud os-login for user login and authentication for VMs.
          See https://cloud.google.com/compute/docs/oslogin
        varType: bool
        defaultValue: true
      - name: num_instances
        description: Number of instances to create. This value is ignored if static_ips is provided.
        varType: number
        defaultValue: 1
      - name: startup_script
        description: Startup script that will be used by the login node VM.
        varType: string
        defaultValue: ""
      - name: instance_template
        description: |
          Self link to a custom instance template. If set, other VM definition
          variables such as machine_type and instance_image will be ignored in favor
          of the provided instance template.

          For more information on creating custom images for the instance template
          that comply with Slurm on GCP see the "Slurm on GCP Custom Images" section
          in docs/vm-images.md.
        varType: string
      - name: instance_image
        description: |
          Defines the image that will be used in the Slurm login node VM instances.

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.

          For more information on creating custom images that comply with Slurm on GCP
          see the "Slurm on GCP Custom Images" section in docs/vm-images.md.
        varType: map(string)
        defaultValue:
          family: slurm-gcp-5-12-hpc-centos-7
          project: schedmd-slurm-public
      - name: instance_image_custom
        description: |
          A flag that designates that the user is aware that they are requesting
          to use a custom and potentially incompatible image for this Slurm on
          GCP module.

          If the field is set to false, only the compatible families and project
          names will be accepted.  The deployment will fail with any other image
          family or name.  If set to true, no checks will be done.

          See: https://goo.gle/hpc-slurm-images
        varType: bool
        defaultValue: false
      - name: allow_automatic_updates
        description: |
          If false, disables automatic system package updates on the created instances.  This feature is
          only available on supported images (or images derived from them).  For more details, see
          https://cloud.google.com/compute/docs/instances/create-hpc-vm#disable_automatic_updates
        varType: bool
        defaultValue: true
      - name: source_image_project
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: source_image_family
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: source_image
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: disk_type
        description: Boot disk type.
        varType: string
        defaultValue: pd-standard
      - name: disk_size_gb
        description: Boot disk size in GB.
        varType: number
        defaultValue: 50
      - name: disk_auto_delete
        description: Whether or not the boot disk should be auto-deleted.
        varType: bool
        defaultValue: true
      - name: disk_labels
        description: Labels specific to the boot disk. These will be merged with var.labels.
        varType: map(string)
        defaultValue: {}
      - name: additional_disks
        description: List of maps of disks.
        varType: |-
          list(object({
              disk_name    = string
              device_name  = string
              disk_type    = string
              disk_size_gb = number
              disk_labels  = map(string)
              auto_delete  = bool
              boot         = bool
            }))
        defaultValue: []
      - name: enable_reconfigure
        description: |
          Enables automatic Slurm reconfigure on when Slurm configuration changes (e.g.
          slurm.conf.tpl, partition details).

          NOTE: Requires Google Pub/Sub API.
        varType: bool
        defaultValue: false
      - name: pubsub_topic
        description: |
          The cluster pubsub topic created by the controller when enable_reconfigure=true.
        varType: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
