apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/internal/slurm-gcp/internal-instance-template-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/internal/slurm-gcp/internal_instance_template
  ui:
    input:
      variables:
        access_config:
          name: access_config
          title: Access Config
        additional_disks:
          name: additional_disks
          title: Additional Disks
        additional_networks:
          name: additional_networks
          title: Additional Networks
        alias_ip_range:
          name: alias_ip_range
          title: Alias Ip Range
        auto_delete:
          name: auto_delete
          title: Auto Delete
        automatic_restart:
          name: automatic_restart
          title: Automatic Restart
        can_ip_forward:
          name: can_ip_forward
          title: Can Ip Forward
        disk_encryption_key:
          name: disk_encryption_key
          title: Disk Encryption Key
        disk_labels:
          name: disk_labels
          title: Disk Labels
        disk_size_gb:
          name: disk_size_gb
          title: Disk Size Gb
        disk_type:
          name: disk_type
          title: Disk Type
        enable_confidential_vm:
          name: enable_confidential_vm
          title: Enable Confidential Vm
        enable_shielded_vm:
          name: enable_shielded_vm
          title: Enable Shielded Vm
        gpu:
          name: gpu
          title: Gpu
        instance_termination_action:
          name: instance_termination_action
          title: Instance Termination Action
        ipv6_access_config:
          name: ipv6_access_config
          title: Ipv6 Access Config
        labels:
          name: labels
          title: Labels
        machine_type:
          name: machine_type
          title: Machine Type
        metadata:
          name: metadata
          title: Metadata
        min_cpu_platform:
          name: min_cpu_platform
          title: Min Cpu Platform
        name_prefix:
          name: name_prefix
          title: Name Prefix
        network:
          name: network
          title: Network
        network_ip:
          name: network_ip
          title: Network Ip
        nic_type:
          name: nic_type
          title: Nic Type
        on_host_maintenance:
          name: on_host_maintenance
          title: On Host Maintenance
        preemptible:
          name: preemptible
          title: Preemptible
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
        service_account:
          name: service_account
          title: Service Account
        shielded_instance_config:
          name: shielded_instance_config
          title: Shielded Instance Config
        source_image:
          name: source_image
          title: Source Image
        source_image_family:
          name: source_image_family
          title: Source Image Family
        source_image_project:
          name: source_image_project
          title: Source Image Project
        spot:
          name: spot
          title: Spot
        stack_type:
          name: stack_type
          title: Stack Type
        startup_script:
          name: startup_script
          title: Startup Script
        subnetwork:
          name: subnetwork
          title: Subnetwork
        subnetwork_project:
          name: subnetwork_project
          title: Subnetwork Project
        tags:
          name: tags
          title: Tags
        threads_per_core:
          name: threads_per_core
          title: Threads Per Core
        total_egress_bandwidth_tier:
          name: total_egress_bandwidth_tier
          title: Total Egress Bandwidth Tier
