apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/internal/slurm-gcp/internal-instance-template
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/internal/slurm-gcp/internal_instance_template
    version: 8.0.1
    actuationTool:
      flavor: Terraform
      version: ">=0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The GCP project ID
        varType: string
      - name: name_prefix
        description: Name prefix for the instance template
        varType: string
        required: true
      - name: machine_type
        description: Machine type to create, e.g. n1-standard-1
        varType: string
        defaultValue: n1-standard-1
      - name: min_cpu_platform
        description: "Specifies a minimum CPU platform. Applicable values are the friendly names of CPU platforms, such as Intel Haswell or Intel Skylake. See the complete list: https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform"
        varType: string
      - name: can_ip_forward
        description: Enable IP forwarding, for NAT instances for example
        varType: string
        defaultValue: "false"
      - name: tags
        description: Network tags, provided as a list
        varType: list(string)
        defaultValue: []
      - name: labels
        description: Labels, provided as a map
        varType: map(string)
        defaultValue: {}
      - name: preemptible
        description: Allow the instance to be preempted
        varType: bool
        defaultValue: false
      - name: spot
        description: |
          Provision as a SPOT preemptible instance.
          See https://cloud.google.com/compute/docs/instances/spot for more details.
        varType: bool
        defaultValue: false
      - name: instance_termination_action
        description: |
          Which action to take when Compute Engine preempts the VM. Value can be: 'STOP', 'DELETE'. The default value is 'STOP'.
          See https://cloud.google.com/compute/docs/instances/spot for more details.
        varType: string
        defaultValue: STOP
      - name: automatic_restart
        description: (Optional) Specifies whether the instance should be automatically restarted if it is terminated by Compute Engine (not terminated by a user).
        varType: bool
        defaultValue: true
      - name: on_host_maintenance
        description: Instance availability Policy
        varType: string
        defaultValue: MIGRATE
      - name: region
        description: Region where the instance template should be created.
        varType: string
      - name: threads_per_core
        description: The number of threads per physical core. To disable simultaneous multithreading (SMT) set this to 1.
        varType: number
      - name: source_image
        description: Source disk image. If neither source_image nor source_image_family is specified, defaults to the latest public CentOS image.
        varType: string
        defaultValue: ""
      - name: source_image_family
        description: Source image family. If neither source_image nor source_image_family is specified, defaults to the latest public CentOS image.
        varType: string
        defaultValue: centos-7
      - name: source_image_project
        description: Project where the source image comes from. The default project contains CentOS images.
        varType: string
        defaultValue: centos-cloud
      - name: disk_size_gb
        description: Boot disk size in GB
        varType: string
        defaultValue: "100"
      - name: disk_type
        description: Boot disk type, can be either pd-ssd, local-ssd, or pd-standard
        varType: string
        defaultValue: pd-standard
      - name: disk_labels
        description: Labels to be assigned to boot disk, provided as a map
        varType: map(string)
        defaultValue: {}
      - name: disk_encryption_key
        description: The id of the encryption key that is stored in Google Cloud KMS to use to encrypt all the disks on this instance
        varType: string
      - name: auto_delete
        description: Whether or not the boot disk should be auto-deleted
        varType: string
        defaultValue: "true"
      - name: additional_disks
        description: List of maps of additional disks. See https://www.terraform.io/docs/providers/google/r/compute_instance_template#disk_name
        varType: |-
          list(object({
              disk_name    = string
              device_name  = string
              auto_delete  = bool
              boot         = bool
              disk_size_gb = number
              disk_type    = string
              disk_labels  = map(string)
            }))
        defaultValue: []
      - name: network
        description: The name or self_link of the network to attach this interface to. Use network attribute for Legacy or Auto subnetted networks and subnetwork for custom subnetted networks.
        varType: string
        defaultValue: ""
      - name: nic_type
        description: "The type of vNIC to be used on this interface. Possible values: GVNIC, VIRTIO_NET."
        varType: string
      - name: subnetwork
        description: The name of the subnetwork to attach this interface to. The subnetwork must exist in the same region this instance will be created in. Either network or subnetwork must be provided.
        varType: string
        defaultValue: ""
      - name: subnetwork_project
        description: The ID of the project in which the subnetwork belongs. If it is not provided, the provider project is used.
        varType: string
      - name: network_ip
        description: Private IP address to assign to the instance if desired.
        varType: string
        defaultValue: ""
      - name: stack_type
        description: The stack type for this network interface to identify whether the IPv6 feature is enabled or not. Values are `IPV4_IPV6` or `IPV4_ONLY`. Default behavior is equivalent to IPV4_ONLY.
        varType: string
      - name: additional_networks
        description: Additional network interface details for GCE, if any.
        varType: |-
          list(object({
              network            = string
              subnetwork         = string
              subnetwork_project = string
              network_ip         = string
              nic_type           = string
              access_config = list(object({
                nat_ip       = string
                network_tier = string
              }))
              ipv6_access_config = list(object({
                network_tier = string
              }))
            }))
        defaultValue: []
      - name: total_egress_bandwidth_tier
        description: |
          Network bandwidth tier. Note: machine_type must be a supported type. Values are 'TIER_1' or 'DEFAULT'.
          See https://cloud.google.com/compute/docs/networking/configure-vm-with-high-bandwidth-configuration for details.
        varType: string
        defaultValue: DEFAULT
      - name: startup_script
        description: User startup script to run when instances spin up
        varType: string
        defaultValue: ""
      - name: metadata
        description: Metadata, provided as a map
        varType: map(string)
        defaultValue: {}
      - name: service_account
        description: Service account to attach to the instance. See https://www.terraform.io/docs/providers/google/r/compute_instance_template#service_account.
        varType: |-
          object({
              email  = optional(string)
              scopes = set(string)
            })
        required: true
      - name: enable_shielded_vm
        description: Whether to enable the Shielded VM configuration on the instance. Note that the instance image must support Shielded VMs. See https://cloud.google.com/compute/docs/images
        varType: bool
        defaultValue: false
      - name: shielded_instance_config
        description: Not used unless enable_shielded_vm is true. Shielded VM configuration for the instance.
        varType: |-
          object({
              enable_secure_boot          = bool
              enable_vtpm                 = bool
              enable_integrity_monitoring = bool
            })
        defaultValue:
          enable_integrity_monitoring: true
          enable_secure_boot: true
          enable_vtpm: true
      - name: enable_confidential_vm
        description: Whether to enable the Confidential VM configuration on the instance. Note that the instance image must support Confidential VMs. See https://cloud.google.com/compute/docs/images
        varType: bool
        defaultValue: false
      - name: access_config
        description: Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet.
        varType: |-
          list(object({
              nat_ip       = string
              network_tier = string
            }))
        defaultValue: []
      - name: ipv6_access_config
        description: IPv6 access configurations. Currently a max of 1 IPv6 access configuration is supported. If not specified, the instance will have no external IPv6 Internet access.
        varType: |-
          list(object({
              network_tier = string
            }))
        defaultValue: []
      - name: gpu
        description: GPU information. Type and count of GPU to attach to the instance template. See https://cloud.google.com/compute/docs/gpus more details
        varType: |-
          object({
              type  = string
              count = number
            })
      - name: alias_ip_range
        description: |
          An array of alias IP ranges for this network interface. Can only be specified for network interfaces on subnet-mode networks.
          ip_cidr_range: The IP CIDR range represented by this alias IP range. This IP CIDR range must belong to the specified subnetwork and cannot contain IP addresses reserved by system or used by other network interfaces. At the time of writing only a netmask (e.g. /24) may be supplied, with a CIDR format resulting in an API error.
          subnetwork_range_name: The subnetwork secondary range name specifying the secondary range from which to allocate the IP CIDR range for this alias IP range. If left unspecified, the primary range of the subnetwork will be used.
        varType: |-
          object({
              ip_cidr_range         = string
              subnetwork_range_name = string
            })
    outputs:
      - name: name
        description: Name of instance template
      - name: self_link
        description: Self-link of instance template
      - name: service_account
        description: value
      - name: tags
        description: Tags that will be associated with instance(s)
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.88"
      - source: hashicorp/google-beta
        version: ">= 6.13.0"
