apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: ai-on-gke-embedded/community/modules/internal/slurm-gcp/instance
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: "Module: Slurm Instance"
    source:
      repo: https://github.com/GoogleCloudPlatform/ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/internal/slurm-gcp/instance
    actuationTool:
      flavor: Terraform
      version: ~> 1.0
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The GCP project ID
        varType: string
      - name: network
        description: Network to deploy to. Only one of network or subnetwork should be specified.
        varType: string
        defaultValue: ""
      - name: subnetwork
        description: Subnet to deploy to. Only one of network or subnetwork should be specified.
        varType: string
        defaultValue: ""
      - name: subnetwork_project
        description: The project that subnetwork belongs to
        varType: string
      - name: hostname
        description: Hostname of instances
        varType: string
        required: true
      - name: additional_networks
        description: Additional network interface details for GCE, if any.
        varType: |-
          list(object({
              access_config = optional(list(object({
                nat_ip       = string
                network_tier = string
              })), [])
              alias_ip_range = optional(list(object({
                ip_cidr_range         = string
                subnetwork_range_name = string
              })), [])
              ipv6_access_config = optional(list(object({
                network_tier = string
              })), [])
              network            = optional(string)
              network_ip         = optional(string, "")
              nic_type           = optional(string)
              queue_count        = optional(number)
              stack_type         = optional(string)
              subnetwork         = optional(string)
              subnetwork_project = optional(string)
            }))
        defaultValue: []
      - name: static_ips
        description: List of static IPs for VM instances
        varType: list(string)
        defaultValue: []
      - name: access_config
        description: Access configurations, i.e. IPs via which the VM instance can be accessed via the Internet.
        varType: |-
          list(object({
              nat_ip       = string
              network_tier = string
            }))
        defaultValue: []
      - name: num_instances
        description: Number of instances to create. This value is ignored if static_ips is provided.
        varType: number
        defaultValue: 1
      - name: instance_template
        description: Instance template self_link used to create compute instances
        varType: string
        required: true
      - name: region
        description: Region where the instances should be created.
        varType: string
      - name: zone
        description: Zone where the instances should be created. If not specified, instances will be spread across available zones in the region.
        varType: string
      - name: replace_trigger
        description: Trigger value to replace the instances.
        varType: string
        defaultValue: ""
    outputs:
      - name: available_zones
        description: List of available zones in region
      - name: instances_details
        description: List of all details for compute instances
      - name: instances_self_links
        description: List of self-links for compute instances
      - name: names
        description: List of available zones in region
      - name: slurm_instances
        description: List of all resource objects for compute instances
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.43"
      - source: hashicorp/null
        version: ~> 3.0
