apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/htcondor-central-manager
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/htcondor-central-manager
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.1.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which HTCondor central manager will be created
        varType: string
        required: true
      - name: deployment_name
        description: Cluster Toolkit deployment name. HTCondor cloud resource names will include this value.
        varType: string
        required: true
      - name: labels
        description: Labels to add to resources. List key, value pairs.
        varType: map(string)
        required: true
      - name: region
        description: Default region for creating resources
        varType: string
        required: true
      - name: zones
        description: Zone(s) in which central manager may be created. If not supplied, will default to all zones in var.region.
        varType: list(string)
        defaultValue: []
      - name: distribution_policy_target_shape
        description: Target shape for instance group managing high availability of central manager
        varType: string
        defaultValue: ANY_SINGLE_ZONE
      - name: network_self_link
        description: The self link of the network in which the HTCondor central manager will be created.
        varType: string
      - name: central_manager_service_account_email
        description: Service account e-mail for central manager (can be supplied by htcondor-setup module)
        varType: string
        required: true
      - name: service_account_scopes
        description: Scopes by which to limit service account attached to central manager.
        varType: set(string)
        defaultValue:
          - https://www.googleapis.com/auth/cloud-platform
      - name: network_storage
        description: An array of network attached storage mounts to be configured
        varType: |-
          list(object({
              server_ip             = string,
              remote_mount          = string,
              local_mount           = string,
              fs_type               = string,
              mount_options         = string,
              client_install_runner = map(string)
              mount_runner          = map(string)
            }))
        defaultValue: []
      - name: disk_size_gb
        description: Boot disk size in GB
        varType: number
        defaultValue: 20
      - name: metadata
        description: Metadata to add to HTCondor central managers
        varType: map(string)
        defaultValue: {}
      - name: enable_oslogin
        description: Enable or Disable OS Login with "ENABLE" or "DISABLE". Set to "INHERIT" to inherit project OS Login setting.
        varType: string
        defaultValue: ENABLE
      - name: subnetwork_self_link
        description: The self link of the subnetwork in which the HTCondor central manager will be created.
        varType: string
      - name: instance_image
        description: |
          Custom VM image with HTCondor installed using the htcondor-install module."

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.
        varType: map(string)
        required: true
      - name: allow_automatic_updates
        description: |
          If false, disables automatic system package updates on the created instances.  This feature is
          only available on supported images (or images derived from them).  For more details, see
          https://cloud.google.com/compute/docs/instances/create-hpc-vm#disable_automatic_updates
        varType: bool
        defaultValue: true
      - name: machine_type
        description: Machine type to use for HTCondor central managers
        varType: string
        defaultValue: n2-standard-4
      - name: central_manager_runner
        description: A list of Toolkit runners for configuring an HTCondor central manager
        varType: list(map(string))
        defaultValue: []
      - name: htcondor_bucket_name
        description: Name of HTCondor configuration bucket
        varType: string
        required: true
      - name: enable_shielded_vm
        description: Enable the Shielded VM configuration (var.shielded_instance_config).
        varType: bool
        defaultValue: false
      - name: shielded_instance_config
        description: Shielded VM configuration for the instance (must set var.enabled_shielded_vm)
        varType: |-
          object({
              enable_secure_boot          = bool
              enable_vtpm                 = bool
              enable_integrity_monitoring = bool
            })
        defaultValue:
          enable_integrity_monitoring: true
          enable_secure_boot: true
          enable_vtpm: true
      - name: update_policy
        description: Replacement policy for Central Manager ("PROACTIVE" to replace immediately or "OPPORTUNISTIC" to replace upon instance power cycle).
        varType: string
        defaultValue: PROACTIVE
    outputs:
      - name: central_manager_ips
        description: IP addresses of the central managers provisioned by this module
      - name: central_manager_name
        description: Name of the central managers provisioned by this module
      - name: list_instances_command
        description: Command to list central managers provisioned by this module
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
