apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/management/kubectl-apply
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/management/kubectl-apply
    version: 1.37.2
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The project ID that hosts the gke cluster.
        varType: string
        required: true
      - name: cluster_id
        description: An identifier for the gke cluster resource with format projects/<project_id>/locations/<region>/clusters/<name>.
        varType: string
        required: true
      - name: apply_manifests
        description: A list of manifests to apply to GKE cluster using kubectl. For more details see [kubectl module's inputs](kubectl/README.md).
        varType: |-
          list(object({
              content           = optional(string, null)
              source            = optional(string, null)
              template_vars     = optional(map(any), null)
              server_side_apply = optional(bool, false)
              wait_for_rollout  = optional(bool, true)
            }))
        defaultValue: []
      - name: kueue
        description: Install and configure [Kueue](https://kueue.sigs.k8s.io/docs/overview/) workload scheduler. A configuration yaml/template file can be provided with config_path to be applied right after kueue installation. If a template file provided, its variables can be set to config_template_vars.
        varType: |-
          object({
              install              = optional(bool, false)
              version              = optional(string, "v0.8.1")
              config_path          = optional(string, null)
              config_template_vars = optional(map(any), null)
            })
        defaultValue: {}
      - name: jobset
        description: Install [Jobset](https://github.com/kubernetes-sigs/jobset) which manages a group of K8s [jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/) as a unit.
        varType: |-
          object({
              install = optional(bool, false)
              version = optional(string, "v0.5.2")
            })
        defaultValue: {}
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: gavinbunney/kubectl
        version: ">= 1.7.0"
      - source: hashicorp/google
        version: "> 5.0"
      - source: hashicorp/http
        version: ~> 3.0
