apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/file-system/ddn-exa-scaler
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/file-system/DDN-EXAScaler
    actuationTool:
      flavor: Terraform
      version: ">= 0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: fsname
        description: EXAScaler filesystem name, only alphanumeric characters are allowed, and the value must be 1-8 characters long
        varType: string
        defaultValue: exacloud
      - name: project_id
        description: Compute Platform project that will host the EXAScaler filesystem
        varType: string
        required: true
      - name: zone
        description: Compute Platform zone where the servers will be located
        varType: string
        required: true
      - name: service_account
        description: Service account name used by deploy application
        varType: |-
          object({
              new   = bool
              email = string
            })
        defaultValue:
          email: null
          new: false
      - name: waiter
        description: Waiter to check progress and result for deployment.
        varType: string
      - name: security
        description: Security options
        varType: |-
          object({
              admin              = string
              public_key         = string
              block_project_keys = bool
              enable_os_login    = bool
              enable_local       = bool
              enable_ssh         = bool
              enable_http        = bool
              ssh_source_ranges  = list(string)
              http_source_ranges = list(string)
            })
        defaultValue:
          admin: stack
          block_project_keys: false
          enable_http: false
          enable_local: false
          enable_os_login: true
          enable_ssh: false
          http_source_ranges:
            - 0.0.0.0/0
          public_key: null
          ssh_source_ranges:
            - 0.0.0.0/0
      - name: network_self_link
        description: The self-link of the VPC network to where the system is connected.  Ignored if 'network_properties' is provided. 'network_self_link' or 'network_properties' must be provided.
        varType: string
      - name: network_properties
        description: Network options. 'network_self_link' or 'network_properties' must be provided.
        varType: |-
          object({
              routing = string
              tier    = string
              id      = string
              auto    = bool
              mtu     = number
              new     = bool
              nat     = bool
            })
      - name: subnetwork_self_link
        description: The self-link of the VPC subnetwork to where the system is connected. Ignored if 'subnetwork_properties' is provided. 'subnetwork_self_link' or 'subnetwork_properties' must be provided.
        varType: string
      - name: subnetwork_address
        description: The IP range of internal addresses for the subnetwork. Ignored if 'subnetwork_properties' is provided.
        varType: string
      - name: subnetwork_properties
        description: Subnetwork properties. 'subnetwork_self_link' or 'subnetwork_properties' must be provided.
        varType: |-
          object({
              address = string
              private = bool
              id      = string
              new     = bool
            })
      - name: boot
        description: Boot disk properties
        varType: |-
          object({
              disk_type   = string
              auto_delete = bool
              script_url  = string
            })
        defaultValue:
          auto_delete: true
          disk_type: pd-standard
          script_url: null
      - name: image
        description: "DEPRECATED: Source image properties"
        varType: any
      - name: instance_image
        description: |
          Source image properties

          Expected Fields:
          name: Unavailable with this module.
          family: The image family to use.
          project: The project where the image is hosted.
        varType: map(string)
        defaultValue:
          family: exascaler-cloud-6-2-rocky-linux-8-optimized-gcp
          project: ddn-public
      - name: mgs
        description: Management server properties
        varType: |-
          object({
              node_type  = string
              node_cpu   = string
              nic_type   = string
              node_count = number
              public_ip  = bool
            })
        defaultValue:
          nic_type: GVNIC
          node_count: 1
          node_cpu: Intel Cascade Lake
          node_type: n2-standard-32
          public_ip: true
      - name: mgt
        description: Management target properties
        varType: |-
          object({
              disk_bus   = string
              disk_type  = string
              disk_size  = number
              disk_count = number
              disk_raid  = bool
            })
        defaultValue:
          disk_bus: SCSI
          disk_count: 1
          disk_raid: false
          disk_size: 128
          disk_type: pd-standard
      - name: mnt
        description: Monitoring target properties
        varType: |-
          object({
              disk_bus   = string
              disk_type  = string
              disk_size  = number
              disk_count = number
              disk_raid  = bool
            })
        defaultValue:
          disk_bus: SCSI
          disk_count: 1
          disk_raid: false
          disk_size: 128
          disk_type: pd-standard
      - name: mds
        description: Metadata server properties
        varType: |-
          object({
              node_type  = string
              node_cpu   = string
              nic_type   = string
              node_count = number
              public_ip  = bool
            })
        defaultValue:
          nic_type: GVNIC
          node_count: 1
          node_cpu: Intel Cascade Lake
          node_type: n2-standard-32
          public_ip: true
      - name: mdt
        description: Metadata target properties
        varType: |-
          object({
              disk_bus   = string
              disk_type  = string
              disk_size  = number
              disk_count = number
              disk_raid  = bool
            })
        defaultValue:
          disk_bus: SCSI
          disk_count: 1
          disk_raid: false
          disk_size: 3500
          disk_type: pd-ssd
      - name: oss
        description: Object Storage server properties
        varType: |-
          object({
              node_type  = string
              node_cpu   = string
              nic_type   = string
              node_count = number
              public_ip  = bool
            })
        defaultValue:
          nic_type: GVNIC
          node_count: 3
          node_cpu: Intel Cascade Lake
          node_type: n2-standard-16
          public_ip: true
      - name: ost
        description: Object Storage target properties
        varType: |-
          object({
              disk_bus   = string
              disk_type  = string
              disk_size  = number
              disk_count = number
              disk_raid  = bool
            })
        defaultValue:
          disk_bus: SCSI
          disk_count: 1
          disk_raid: false
          disk_size: 3500
          disk_type: pd-ssd
      - name: cls
        description: Compute client properties
        varType: |-
          object({
              node_type  = string
              node_cpu   = string
              nic_type   = string
              node_count = number
              public_ip  = bool
            })
        defaultValue:
          nic_type: GVNIC
          node_count: 0
          node_cpu: Intel Cascade Lake
          node_type: n2-standard-2
          public_ip: true
      - name: clt
        description: Compute client target properties
        varType: |-
          object({
              disk_bus   = string
              disk_type  = string
              disk_size  = number
              disk_count = number
            })
        defaultValue:
          disk_bus: SCSI
          disk_count: 0
          disk_size: 256
          disk_type: pd-standard
      - name: local_mount
        description: Mountpoint (at the client instances) for this EXAScaler system
        varType: string
        defaultValue: /shared
      - name: prefix
        description: EXAScaler Cloud deployment prefix (`null` defaults to 'exascaler-cloud')
        varType: string
      - name: labels
        description: Labels to add to EXAScaler Cloud deployment. Key-value pairs.
        varType: map(string)
        defaultValue: {}
    outputs:
      - name: client_config_script
        description: Script that will install DDN EXAScaler lustre client. The machine running this script must be on the same network & subnet as the EXAScaler.
      - name: http_console
        description: HTTP address to access the system web console.
      - name: install_ddn_lustre_client_runner
        description: Runner that encapsulates the `client_config_script` output on this module.
      - name: mount_command
        description: Command to mount the file system. `client_config_script` must be run first.
      - name: mount_runner
        description: Runner to mount the DDN EXAScaler Lustre file system
      - name: network_storage
        description: Describes a EXAScaler system to be mounted by other systems.
      - name: private_addresses
        description: Private IP addresses for all instances.
      - name: ssh_console
        description: Instructions to ssh into the instances.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
