apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/pbspro-client
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/pbspro-client
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which Google Cloud resources will be created
        varType: string
        required: true
      - name: deployment_name
        description: Cluster Toolkit deployment name. Cloud resource names will include this value.
        varType: string
        required: true
      - name: region
        description: Default region for creating resources
        varType: string
        required: true
      - name: zone
        description: Default zone for creating resources
        varType: string
        required: true
      - name: pbs_exec
        description: Root path in which to install PBS
        varType: string
        defaultValue: /opt/pbs
      - name: pbs_home
        description: PBS working directory
        varType: string
        defaultValue: /var/spool/pbs
      - name: pbs_server
        description: IP address or DNS name of PBS server host
        varType: string
        required: true
      - name: pbs_client_rpm_url
        description: Path to PBS Pro Client Host RPM file
        varType: string
        required: true
      - name: name_prefix
        description: Name prefix for PBS execution hostnames
        varType: string
      - name: instance_count
        description: Number of instances
        varType: number
        defaultValue: 1
      - name: network_storage
        description: An array of network attached storage mounts to be configured.
        varType: |-
          list(object({
              server_ip             = string,
              remote_mount          = string,
              local_mount           = string,
              fs_type               = string,
              mount_options         = string,
              client_install_runner = map(string)
              mount_runner          = map(string)
            }))
        defaultValue: []
      - name: instance_image
        description: |
          Instance Image

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.
        varType: map(string)
        defaultValue:
          name: hpc-centos-7-v20240712
          project: cloud-hpc-image-public
      - name: disk_size_gb
        description: Size of disk for instances.
        varType: number
        defaultValue: 200
      - name: disk_type
        description: Disk type for instances.
        varType: string
        defaultValue: pd-standard
      - name: auto_delete_boot_disk
        description: Controls if boot disk should be auto-deleted when instance is deleted.
        varType: bool
        defaultValue: true
      - name: local_ssd_count
        description: The number of local SSDs to attach to each VM. See https://cloud.google.com/compute/docs/disks/local-ssd.
        varType: number
        defaultValue: 0
      - name: local_ssd_interface
        description: Interface to be used with local SSDs. Can be either 'NVME' or 'SCSI'. No effect unless `local_ssd_count` is also set.
        varType: string
        defaultValue: NVME
      - name: enable_public_ips
        description: If set to true, instances will have public IPs on the internet.
        varType: bool
        defaultValue: true
      - name: machine_type
        description: Machine type to use for the instance creation
        varType: string
        defaultValue: c2-standard-60
      - name: labels
        description: Labels to add to the instances. Key-value pairs.
        varType: map(string)
        required: true
      - name: service_account
        description: Service account to attach to the instance. See https://www.terraform.io/docs/providers/google/r/compute_instance_template.html#service_account.
        varType: |-
          object({
              email  = string,
              scopes = set(string)
            })
        defaultValue:
          email: null
          scopes:
            - https://www.googleapis.com/auth/devstorage.read_write
            - https://www.googleapis.com/auth/logging.write
            - https://www.googleapis.com/auth/monitoring.write
            - https://www.googleapis.com/auth/servicecontrol
            - https://www.googleapis.com/auth/service.management.readonly
            - https://www.googleapis.com/auth/trace.append
      - name: network_self_link
        description: The self link of the network to attach the VM.
        varType: string
        defaultValue: default
      - name: subnetwork_self_link
        description: The self link of the subnetwork to attach the VM.
        varType: string
      - name: network_interfaces
        description: |
          A list of network interfaces. The options match that of the terraform
          network_interface block of google_compute_instance. For descriptions of the
          subfields or more information see the documentation:
          https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#nested_network_interface

          **_NOTE:_** If `network_interfaces` are set, `network_self_link` and
          `subnetwork_self_link` will be ignored, even if they are provided through
          the `use` field. `bandwidth_tier` and `enable_public_ips` also do not apply
          to network interfaces defined in this variable.

          Subfields:
          network            (string, required if subnetwork is not supplied)
          subnetwork         (string, required if network is not supplied)
          subnetwork_project (string, optional)
          network_ip         (string, optional)
          nic_type           (string, optional, choose from ["GVNIC", "VIRTIO_NET"])
          stack_type         (string, optional, choose from ["IPV4_ONLY", "IPV4_IPV6"])
          queue_count        (number, optional)
          access_config      (object, optional)
          ipv6_access_config (object, optional)
          alias_ip_range     (list(object), optional)
        varType: |-
          list(object({
              network            = string,
              subnetwork         = string,
              subnetwork_project = string,
              network_ip         = string,
              nic_type           = string,
              stack_type         = string,
              queue_count        = number,
              access_config = list(object({
                nat_ip                 = string,
                public_ptr_domain_name = string,
                network_tier           = string
              })),
              ipv6_access_config = list(object({
                public_ptr_domain_name = string,
                network_tier           = string
              })),
              alias_ip_range = list(object({
                ip_cidr_range         = string,
                subnetwork_range_name = string
              }))
            }))
        defaultValue: []
      - name: metadata
        description: Metadata, provided as a map
        varType: map(string)
        defaultValue: {}
      - name: startup_script
        description: Startup script used on the instance
        varType: string
      - name: guest_accelerator
        description: List of the type and count of accelerator cards attached to the instance.
        varType: |-
          list(object({
              type  = string,
              count = number
            }))
      - name: on_host_maintenance
        description: Describes maintenance behavior for the instance. If left blank this will default to `MIGRATE` except for when `placement_policy`, spot provisioning, or GPUs require it to be `TERMINATE`
        varType: string
      - name: bandwidth_tier
        description: "  Tier 1 bandwidth increases the maximum egress bandwidth for VMs.\n  Using the `tier_1_enabled` setting will enable both gVNIC and TIER_1 higher bandwidth networking.\n  Using the `gvnic_enabled` setting will only enable gVNIC and will not enable TIER_1.\n  Note that TIER_1 only works with specific machine families & shapes and must be using an image th\nat supports gVNIC. See [official docs](https://cloud.google.com/compute/docs/networking/configure-v\nm-with-high-bandwidth-configuration) for more details.\n"
        varType: string
        defaultValue: not_enabled
      - name: placement_policy
        description: Control where your VM instances are physically located relative to each other within a zone.
        varType: |-
          object({
              vm_count                  = number,
              availability_domain_count = number,
              collocation               = string,
            })
      - name: spot
        description: Provision VMs using discounted Spot pricing, allowing for preemption
        varType: bool
        defaultValue: false
      - name: tags
        description: Network tags, provided as a list
        varType: list(string)
        defaultValue: []
      - name: threads_per_core
        description: |
          Sets the number of threads per physical core. By setting threads_per_core
          to 2, Simultaneous Multithreading (SMT) is enabled extending the total number
          of virtual cores. For example, a machine of type c2-standard-60 will have 60
          virtual cores with threads_per_core equal to 2. With threads_per_core equal
          to 1 (SMT turned off), only the 30 physical cores will be available on the VM.

          The default value of \"0\" will turn off SMT for supported machine types, and
          will fall back to GCE defaults for unsupported machine types (t2d, shared-core
          instances, or instances with less than 2 vCPU).

          Disabling SMT can be more performant in many HPC workloads, therefore it is
          disabled by default where compatible.

          null = SMT configuration will use the GCE defaults for the machine type
          0 = SMT will be disabled where compatible (default)
          1 = SMT will always be disabled (will fail on incompatible machine types)
          2 = SMT will always be enabled (will fail on incompatible machine types)
        varType: number
        defaultValue: 0
      - name: enable_oslogin
        description: Enable or Disable OS Login with "ENABLE" or "DISABLE". Set to "INHERIT" to inherit project OS Login setting.
        varType: string
        defaultValue: ENABLE
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
