apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/compute/mig
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/compute/mig
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the MIG will be created
        varType: string
        required: true
      - name: deployment_name
        description: Name of the deployment, will be used to name MIG if `var.name` is not provided
        varType: string
        required: true
      - name: labels
        description: Labels to add to the MIG
        varType: map(string)
        required: true
      - name: zone
        description: Compute Platform zone. Required, currently only zonal MIGs are supported
        varType: string
        required: true
      - name: versions
        description: |
          Application versions managed by this instance group. Each version deals with a specific instance template
        varType: |-
          list(object({
              name              = string
              instance_template = string
              target_size = optional(object({
                fixed   = optional(number)
                percent = optional(number)
              }))
            }))
        required: true
      - name: ghpc_module_id
        description: Internal GHPC field, do not set this value
        varType: string
      - name: name
        description: Name of the MIG. If not provided, will be generated from `var.deployment_name`
        varType: string
      - name: base_instance_name
        description: Base name for the instances in the MIG
        varType: string
      - name: target_size
        description: Target number of instances in the MIG
        varType: number
        defaultValue: 0
      - name: wait_for_instances
        description: Whether to wait for all instances to be created/updated before returning
        varType: bool
        defaultValue: false
    outputs:
      - name: self_link
        description: The URL of the created MIG
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: "> 5.0"
