apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/database/bigquery-table
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/database/bigquery-table
    actuationTool:
      flavor: Terraform
      version: ">= 1.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: deployment_name
        description: The name of the current deployment
        varType: string
        required: true
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: labels
        description: Labels to add to the tables. Key-value pairs.
        varType: map(string)
        required: true
      - name: table_id
        description: Table name to be used to create the new BQ Table
        varType: string
      - name: dataset_id
        description: Dataset name to be used to create the new BQ Table
        varType: string
        required: true
      - name: table_schema
        description: Schema used to create the new BQ Table
        varType: string
        required: true
    outputs:
      - name: dataset_id
        description: ID of BQ dataset
      - name: table_id
        description: ID of created BQ table
      - name: table_name
        description: Name of created BQ table
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.42"
      - source: hashicorp/random
        version: ~> 3.0
