apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/compute/schedmd-slurm-gcp-v-6-nodeset-tpu
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: node_count_static
        description: |
          Number of worker nodes to be statically created. 
          For larger TPU machines, there are multiple worker nodes required per machine (1 for every 8 cores).
          See https://cloud.google.com/tpu/docs/v4#large-topologies, for more information about these machine types.
        varType: number
        defaultValue: 0
      - name: node_count_dynamic_max
        description: |
          Maximum number of auto-scaling worker nodes allowed in this partition. 
          For larger TPU machines, there are multiple worker nodes required per machine (1 for every 8 cores).
          See https://cloud.google.com/tpu/docs/v4#large-topologies, for more information about these machine types.
        varType: number
        defaultValue: 0
      - name: name
        description: |
          Name of the nodeset. Automatically populated by the module id if not set. 
          If setting manually, ensure a unique value across all nodesets.
        varType: string
        required: true
      - name: enable_public_ips
        description: If set to true. The node group VMs will have a random public IP assigned to it. Ignored if access_config is set.
        varType: bool
        defaultValue: false
      - name: disable_public_ips
        description: "DEPRECATED: Use `enable_public_ips` instead."
        varType: bool
      - name: node_type
        description: Specify a node type to base the vm configuration upon it.
        varType: string
        defaultValue: ""
      - name: accelerator_config
        description: Nodeset accelerator config, see https://cloud.google.com/tpu/docs/supported-tpu-configurations for details.
        varType: |-
          object({
              topology = string
              version  = string
            })
        defaultValue:
          topology: ""
          version: ""
      - name: tf_version
        description: Nodeset Tensorflow version, see https://cloud.google.com/tpu/docs/supported-tpu-configurations#tpu_vm for details.
        varType: string
        defaultValue: 2.14.0
      - name: preemptible
        description: Should use preemptibles to burst.
        varType: bool
        defaultValue: false
      - name: preserve_tpu
        description: Specify whether TPU-vms will get preserve on suspend, if set to true, on suspend vm is stopped, on false it gets deleted
        varType: bool
        defaultValue: false
      - name: zone
        description: Zone in which to create compute VMs. TPU partitions can only specify a single zone.
        varType: string
        required: true
      - name: data_disks
        description: The data disks to include in the TPU node
        varType: list(string)
        defaultValue: []
      - name: docker_image
        description: The gcp container registry id docker image to use in the TPU vms, it defaults to gcr.io/schedmd-slurm-public/tpu:slurm-gcp-6-8-tf-<var.tf_version>
        varType: string
      - name: subnetwork_self_link
        description: The name of the subnetwork to attach the TPU-vm of this nodeset to.
        varType: string
        required: true
      - name: service_account_email
        description: Service account e-mail address to attach to the TPU-vm.
        varType: string
      - name: service_account_scopes
        description: Scopes to attach to the TPU-vm.
        varType: set(string)
        defaultValue:
          - https://www.googleapis.com/auth/cloud-platform
      - name: service_account
        description: "DEPRECATED: Use `service_account_email` and `service_account_scopes` instead."
        varType: |-
          object({
              email  = string
              scopes = set(string)
            })
      - name: project_id
        description: Project ID to create resources in.
        varType: string
        required: true
      - name: reserved
        description: Specify whether TPU-vms in this nodeset are created under a reservation.
        varType: bool
        defaultValue: false
      - name: network_storage
        description: An array of network attached storage mounts to be configured on nodes.
        varType: |-
          list(object({
              server_ip     = string,
              remote_mount  = string,
              local_mount   = string,
              fs_type       = string,
              mount_options = string,
            }))
        defaultValue: []
    outputs:
      - name: nodeset_tpu
        description: Details of the nodeset tpu. Typically used as input to `schedmd-slurm-gcp-v6-partition`.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
