apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/ramble-setup
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/ramble-setup
    actuationTool:
      flavor: Terraform
      version: ">= 1.0.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created.
        varType: string
        required: true
      - name: install_dir
        description: Destination directory of installation of Ramble.
        varType: string
        defaultValue: /apps/ramble
      - name: ramble_url
        description: URL for Ramble repository to clone.
        varType: string
        defaultValue: https://github.com/GoogleCloudPlatform/ramble
      - name: ramble_ref
        description: Git ref to checkout for Ramble.
        varType: string
        defaultValue: develop
      - name: chmod_mode
        description: |
          Mode to chmod the Ramble clone to. Defaults to `""` (i.e. do not modify).
          For usage information see:
          https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-mode
        varType: string
        defaultValue: ""
      - name: system_user_name
        description: Name of system user that will perform installation of Ramble. It will be created if it does not exist.
        varType: string
        defaultValue: ramble
      - name: system_user_uid
        description: UID used when creating system user. Ignored if `system_user_name` already exists on system. Default of 1104762904 is arbitrary.
        varType: number
        defaultValue: 1104762904
      - name: system_user_gid
        description: GID used when creating system user group. Ignored if `system_user_name` already exists on system. Default of 1104762904 is arbitrary.
        varType: number
        defaultValue: 1104762904
      - name: ramble_virtualenv_path
        description: Virtual environment path in which to install Ramble Python interpreter and other dependencies
        varType: string
        defaultValue: /usr/local/ramble-python
      - name: deployment_name
        description: Name of deployment, used to name bucket containing startup script.
        varType: string
        required: true
      - name: region
        description: Region to place bucket containing startup script.
        varType: string
        required: true
      - name: labels
        description: Key-value pairs of labels to be added to created resources.
        varType: map(string)
        required: true
      - name: ramble_profile_script_path
        description: Path to the Ramble profile.d script. Created by this module
        varType: string
        defaultValue: /etc/profile.d/ramble.sh
    outputs:
      - name: controller_startup_script
        description: Ramble installation script, duplicate for SLURM controller.
      - name: gcs_bucket_path
        description: Bucket containing the startup scripts for Ramble, to be reused by ramble-execute module.
      - name: ramble_path
        description: Location ramble is installed into.
      - name: ramble_profile_script_path
        description: Path to Ramble profile script.
      - name: ramble_ref
        description: Git ref the ramble install is checked out to use
      - name: ramble_runner
        description: |
          Runner to be used with startup-script module or passed to ramble-execute module.
          - installs Ramble dependencies
          - installs Ramble
          - generates profile.d script to enable access to Ramble
          This is safe to run in parallel by multiple machines.
      - name: startup_script
        description: Ramble installation script.
      - name: system_user_name
        description: The system user used to install Ramble. It can be reused by ramble-execute module to execute Ramble commands.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.42"
      - source: hashicorp/local
        version: ">= 2.0.0"
