apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/spack-execute
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/spack-execute
    actuationTool:
      flavor: Terraform
      version: ">= 1.0.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created.
        varType: string
        required: true
      - name: deployment_name
        description: Name of deployment, used to name bucket containing spack scripts.
        varType: string
        required: true
      - name: region
        description: Region to place bucket containing spack scripts.
        varType: string
        required: true
      - name: labels
        description: Key-value pairs of labels to be added to created resources.
        varType: map(string)
        required: true
      - name: log_file
        description: Defines the logfile that script output will be written to
        varType: string
        defaultValue: /var/log/spack.log
      - name: data_files
        description: |
          A list of files to be transferred prior to running commands. 
          It must specify one of 'source' (absolute local file path) or 'content' (string).
          It must specify a 'destination' with absolute path where file should be placed.
        varType: list(map(string))
        defaultValue: []
      - name: commands
        description: String of commands to run within this module
        varType: string
      - name: spack_runner
        description: Runner from previous spack-setup or spack-execute to be chained with scripts generated by this module.
        varType: |-
          object({
              type        = string
              content     = string
              destination = string
            })
        required: true
      - name: system_user_name
        description: Name of the system user used to execute commands. Generally passed from the spack-setup module.
        varType: string
        required: true
      - name: gcs_bucket_path
        description: The GCS path for storage bucket and the object, starting with `gs://`.
        varType: string
        required: true
      - name: spack_profile_script_path
        description: |
          Path to the Spack profile.d script. Created by an instance of spack-setup.
          Can be defined explicitly, or by chaining an instance of a spack-setup module
          through a `use` setting.
        varType: string
        required: true
    outputs:
      - name: controller_startup_script
        description: Spack startup script, duplicate for SLURM controller.
      - name: gcs_bucket_path
        description: Bucket containing the startup scripts for spack, to be reused by spack-execute module.
      - name: spack_profile_script_path
        description: Path to the Spack profile.d script.
      - name: spack_runner
        description: Single runner that combines scripts from this module and any previously chained spack-execute or spack-setup modules.
      - name: startup_script
        description: Spack startup script.
      - name: system_user_name
        description: The system user used to execute commands.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/local
        version: ">= 2.0.0"
