apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/files/fsi-montecarlo-on-batch
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/files/fsi-montecarlo-on-batch
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: ID of project in which GCS bucket will be created.
        varType: string
        required: true
      - name: gcs_bucket_path
        description: Bucket name
        varType: string
      - name: topic_id
        description: Pubsub Topic Name
        varType: string
        required: true
      - name: topic_schema
        description: Pubsub Topic schema
        varType: string
        required: true
      - name: dataset_id
        description: Bigquery dataset id
        varType: string
        required: true
      - name: table_id
        description: Bigquery table id
        varType: string
        required: true
      - name: region
        description: Region to run project
        varType: string
        required: true
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
      - source: hashicorp/http
        version: ~> 3.0
      - source: hashicorp/random
        version: ~> 3.0
      - source: hashicorp/template
        version: ~> 2.0
