apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/network/firewall-rules
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/network/firewall-rules
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: subnetwork_self_link
        description: The self link of the subnetwork whose global network firewall rules will be modified.
        varType: string
        required: true
      - name: ingress_rules
        description: List of ingress rules
        varType: |-
          list(object({
              name                    = string
              description             = optional(string, null)
              disabled                = optional(bool, null)
              priority                = optional(number, null)
              destination_ranges      = optional(list(string), [])
              source_ranges           = optional(list(string), [])
              source_tags             = optional(list(string))
              source_service_accounts = optional(list(string))
              target_tags             = optional(list(string))
              target_service_accounts = optional(list(string))

              allow = optional(list(object({
                protocol = string
                ports    = optional(list(string))
              })), [])
              deny = optional(list(object({
                protocol = string
                ports    = optional(list(string))
              })), [])
              log_config = optional(object({
                metadata = string
              }))
            }))
        defaultValue: []
      - name: egress_rules
        description: List of egress rules
        varType: |-
          list(object({
              name                    = string
              description             = optional(string, null)
              disabled                = optional(bool, null)
              priority                = optional(number, null)
              destination_ranges      = optional(list(string), [])
              source_ranges           = optional(list(string), [])
              source_tags             = optional(list(string))
              source_service_accounts = optional(list(string))
              target_tags             = optional(list(string))
              target_service_accounts = optional(list(string))

              allow = optional(list(object({
                protocol = string
                ports    = optional(list(string))
              })), [])
              deny = optional(list(object({
                protocol = string
                ports    = optional(list(string))
              })), [])
              log_config = optional(object({
                metadata = string
              }))
            }))
        defaultValue: []
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
