apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/compute/schedmd-slurm-gcp-v-5-node-group
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/compute/schedmd-slurm-gcp-v5-node-group
    version: 1.41.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.1"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created.
        varType: string
        required: true
      - name: name
        description: Name of the node group.
        varType: string
        defaultValue: ghpc
      - name: node_conf
        description: Map of Slurm node line configuration.
        varType: map(any)
        defaultValue: {}
      - name: node_count_dynamic_max
        description: Maximum number of auto-scaling nodes allowed in this partition.
        varType: number
        defaultValue: 10
      - name: node_count_static
        description: Number of nodes to be statically created.
        varType: number
        defaultValue: 0
      - name: instance_template
        description: |
          Self link to a custom instance template. If set, other VM definition
          variables such as machine_type and instance_image will be ignored in favor
          of the provided instance template.

          For more information on creating custom images for the instance template
          that comply with Slurm on GCP see the "Slurm on GCP Custom Images" section
          in docs/vm-images.md.
        varType: string
      - name: machine_type
        description: Compute Platform machine type to use for this partition compute nodes.
        varType: string
        defaultValue: c2-standard-60
      - name: metadata
        description: Metadata, provided as a map.
        varType: map(string)
        defaultValue: {}
      - name: instance_image
        description: |
          Defines the image that will be used in the Slurm node group VM instances.

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.

          For more information on creating custom images that comply with Slurm on GCP
          see the "Slurm on GCP Custom Images" section in docs/vm-images.md.
        varType: map(string)
        defaultValue:
          family: slurm-gcp-5-12-hpc-centos-7
          project: schedmd-slurm-public
      - name: instance_image_custom
        description: |
          A flag that designates that the user is aware that they are requesting
          to use a custom and potentially incompatible image for this Slurm on
          GCP module.

          If the field is set to false, only the compatible families and project
          names will be accepted.  The deployment will fail with any other image
          family or name.  If set to true, no checks will be done.

          See: https://goo.gle/hpc-slurm-images
        varType: bool
        defaultValue: false
      - name: source_image_project
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: source_image_family
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: source_image
        description: "DEPRECATED: Use `instance_image` instead."
        varType: string
      - name: tags
        description: Network tag list.
        varType: list(string)
        defaultValue: []
      - name: disk_type
        description: Boot disk type.
        varType: string
        defaultValue: pd-standard
      - name: disk_size_gb
        description: Size of boot disk to create for the partition compute nodes.
        varType: number
        defaultValue: 50
      - name: disk_auto_delete
        description: Whether or not the boot disk should be auto-deleted.
        varType: bool
        defaultValue: true
      - name: disk_labels
        description: Labels specific to the boot disk. These will be merged with var.labels.
        varType: map(string)
        defaultValue: {}
      - name: additional_disks
        description: Configurations of additional disks to be included on the partition nodes.
        varType: |-
          list(object({
              disk_name    = string
              device_name  = string
              disk_size_gb = number
              disk_type    = string
              disk_labels  = map(string)
              auto_delete  = bool
              boot         = bool
            }))
        defaultValue: []
      - name: enable_confidential_vm
        description: "Enable the Confidential VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: enable_shielded_vm
        description: "Enable the Shielded VM configuration. Note: the instance image must support option."
        varType: bool
        defaultValue: false
      - name: enable_oslogin
        description: |
          Enables Google Cloud os-login for user login and authentication for VMs.
          See https://cloud.google.com/compute/docs/oslogin
        varType: bool
        defaultValue: true
      - name: can_ip_forward
        description: Enable IP forwarding, for NAT instances for example.
        varType: bool
        defaultValue: false
      - name: enable_smt
        description: Enables Simultaneous Multi-Threading (SMT) on instance.
        varType: bool
        defaultValue: false
      - name: labels
        description: Labels to add to partition compute instances. Key-value pairs.
        varType: map(string)
        defaultValue: {}
      - name: min_cpu_platform
        description: The name of the minimum CPU platform that you want the instance to use.
        varType: string
      - name: on_host_maintenance
        description: |
          Instance availability Policy.

          Note: Placement groups are not supported when on_host_maintenance is set to
          "MIGRATE" and will be deactivated regardless of the value of
          enable_placement. To support enable_placement, ensure on_host_maintenance is
          set to "TERMINATE".
        varType: string
        defaultValue: TERMINATE
      - name: gpu
        description: "DEPRECATED: use var.guest_accelerator"
        varType: |-
          object({
              type  = string
              count = number
            })
      - name: guest_accelerator
        description: List of the type and count of accelerator cards attached to the instance.
        varType: |-
          list(object({
              type  = string,
              count = number
            }))
        defaultValue: []
      - name: preemptible
        description: Should use preemptibles to burst.
        varType: bool
        defaultValue: false
      - name: reservation_name
        description: |
          Name of the reservation to use for VM resources
          - Must be a "SPECIFIC" reservation
          - Set to empty string if using no reservation or automatically-consumed reservations
        varType: string
        defaultValue: ""
      - name: service_account
        description: |
          Service account to attach to the compute instances. If not set, the
          default compute service account for the given project will be used with the
          "https://www.googleapis.com/auth/cloud-platform" scope.
        varType: |-
          object({
              email  = string
              scopes = set(string)
            })
      - name: shielded_instance_config
        description: |
          Shielded VM configuration for the instance. Note: not used unless
          enable_shielded_vm is 'true'.
          - enable_integrity_monitoring : Compare the most recent boot measurements to the
            integrity policy baseline and return a pair of pass/fail results depending on
            whether they match or not.
          - enable_secure_boot : Verify the digital signature of all boot components, and
            halt the boot process if signature verification fails.
          - enable_vtpm : Use a virtualized trusted platform module, which is a
            specialized computer chip you can use to encrypt objects like keys and
            certificates.
        varType: |-
          object({
              enable_integrity_monitoring = bool
              enable_secure_boot          = bool
              enable_vtpm                 = bool
            })
        defaultValue:
          enable_integrity_monitoring: true
          enable_secure_boot: true
          enable_vtpm: true
      - name: enable_spot_vm
        description: Enable the partition to use spot VMs (https://cloud.google.com/spot-vms).
        varType: bool
        defaultValue: false
      - name: spot_instance_config
        description: Configuration for spot VMs.
        varType: |-
          object({
              termination_action = string
            })
      - name: bandwidth_tier
        description: "  Configures the network interface card and the maximum egress bandwidth for VMs.\n  - Setting `platform_default` respects the Google Cloud Platform API default values for networking.\n  - Setting `virtio_enabled` explicitly selects the VirtioNet network adapter.\n  - Setting `gvnic_enabled` selects the gVNIC network adapter (without Tier 1 high bandwidth).\n  - Setting `tier_1_enabled` selects both the gVNIC adapter and Tier 1 high bandwidth networking.\n  - Note: both gVNIC and Tier 1 networking require a VM image with gVNIC support as well as specific VM families and shapes.\n  - See [official docs](https://cloud.google.com/compute/docs/networking/configure-vm-with-high-bandwidth-configuration) for more details.\n"
        varType: string
        defaultValue: platform_default
      - name: access_config
        description: Access configurations, i.e. IPs via which the node group instances can be accessed via the internet.
        varType: |-
          list(object({
              nat_ip       = string
              network_tier = string
            }))
        defaultValue: []
      - name: additional_networks
        description: Additional network interface details for GCE, if any.
        varType: |-
          list(object({
              network            = string
              subnetwork         = string
              subnetwork_project = string
              network_ip         = string
              nic_type           = string
              stack_type         = string
              queue_count        = number
              access_config = list(object({
                nat_ip       = string
                network_tier = string
              }))
              ipv6_access_config = list(object({
                network_tier = string
              }))
              alias_ip_range = list(object({
                ip_cidr_range         = string
                subnetwork_range_name = string
              }))
            }))
        defaultValue: []
      - name: maintenance_interval
        description: Specifies the frequency of planned maintenance events. Must be "PERIODIC" or empty string to not use this feature.
        varType: string
        defaultValue: ""
      - name: disable_public_ips
        description: If set to false. The node group VMs will have a random public IP assigned to it. Ignored if access_config is set.
        varType: bool
        defaultValue: true
      - name: allow_automatic_updates
        description: |
          If false, disables automatic system package updates on the created instances.  This feature is
          only available on supported images (or images derived from them).  For more details, see
          https://cloud.google.com/compute/docs/instances/create-hpc-vm#disable_automatic_updates
        varType: bool
        defaultValue: true
    outputs:
      - name: node_groups
        description: Details of the node group. Typically used as input to `schedmd-slurm-gcp-v5-partition`.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 5.11"
