apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: ai-on-gke-gcs-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/gcs
  ui:
    input:
      variables:
        bucket_name:
          name: bucket_name
          title: Bucket Name
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
