apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: ai-on-gke-gcs
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GCS bucket used in the RAG on GKE demo
    source:
      repo: https://github.com/GoogleCloudPlatform/ai-on-gke
      sourceType: git
      dir: /modules/gcs
    actuationTool:
      flavor: Terraform
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: GCP project id
        varType: string
        required: true
      - name: region
        description: GCS bucket region
        varType: string
        defaultValue: us-central1
      - name: bucket_name
        description: GCS bucket name
        varType: string
        required: true
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
