apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/scheduler/batch-job-template
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/scheduler/batch-job-template
    actuationTool:
      flavor: Terraform
      version: ">= 1.1"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: region
        description: The region in which to run the Google Cloud Batch job
        varType: string
        required: true
      - name: deployment_name
        description: Name of the deployment, used for the job_id
        varType: string
        required: true
      - name: labels
        description: Labels to add to the Google Cloud Batch compute nodes. Key-value pairs. Ignored if `instance_template` is provided.
        varType: map(string)
        required: true
      - name: job_id
        description: An id for the Google Cloud Batch job. Used for output instructions and file naming. Automatically populated by the module id if not set. If setting manually, ensure a unique value across all jobs.
        varType: string
        required: true
      - name: job_filename
        description: The filename of the generated job template file. Will default to `cloud-batch-<job_id>.json` if not specified
        varType: string
      - name: gcloud_version
        description: The version of the gcloud cli being used. Used for output instructions. Valid inputs are `"alpha"`, `"beta"` and "" (empty string for default version)
        varType: string
        defaultValue: ""
      - name: task_count
        description: Number of parallel tasks
        varType: number
        defaultValue: 1
      - name: task_count_per_node
        description: Max number of tasks that can be run on a VM at the same time. If not specified, Batch will decide a value.
        varType: number
      - name: mpi_mode
        description: Sets up barriers before and after each runnable. In addition, sets `permissiveSsh=true`, `requireHostsFile=true`, and `taskCountPerNode=1`. `taskCountPerNode` can be overridden by `task_count_per_node`.
        varType: bool
        defaultValue: false
      - name: log_policy
        description: |
          Create a block to define log policy.
          When set to `CLOUD_LOGGING`, logs will be sent to Cloud Logging.
          When set to `PATH`, path must be added to generated template.
          When set to `DESTINATION_UNSPECIFIED`, logs will not be preserved.
        varType: string
        defaultValue: CLOUD_LOGGING
      - name: runnables
        description: A list of shell scripts to be executed in sequence as the main workload of the Google Batch job. These will be used to populate the generated template.
        varType: |-
          list(object({
              script = string
            }))
      - name: runnable
        description: A simplified form of `var.runnables` that only takes a single script. Use either `runnables` or `runnable`.
        varType: string
      - name: instance_template
        description: Compute VM instance template self-link to be used for Google Cloud Batch compute node. If provided, a number of other variables will be ignored as noted by `Ignored if instance_template is provided` in descriptions.
        varType: string
      - name: subnetwork
        description: The subnetwork that the Batch job should run on. Defaults to 'default' subnet. Ignored if `instance_template` is provided.
        varType: any
      - name: enable_public_ips
        description: If set to true, instances will have public IPs
        varType: bool
        defaultValue: true
      - name: service_account
        description: Service account to attach to the Google Cloud Batch compute node. Ignored if `instance_template` is provided.
        varType: |-
          object({
              email  = string,
              scopes = set(string)
            })
        defaultValue:
          email: null
          scopes:
            - https://www.googleapis.com/auth/devstorage.read_only
            - https://www.googleapis.com/auth/logging.write
            - https://www.googleapis.com/auth/monitoring.write
            - https://www.googleapis.com/auth/servicecontrol
            - https://www.googleapis.com/auth/service.management.readonly
            - https://www.googleapis.com/auth/trace.append
      - name: machine_type
        description: Machine type to use for Google Cloud Batch compute nodes. Ignored if `instance_template` is provided.
        varType: string
        defaultValue: n2-standard-4
      - name: startup_script
        description: Startup script run before Google Cloud Batch job starts. Ignored if `instance_template` is provided.
        varType: string
      - name: network_storage
        description: An array of network attached storage mounts to be configured. Ignored if `instance_template` is provided.
        varType: |-
          list(object({
              server_ip             = string
              remote_mount          = string
              local_mount           = string
              fs_type               = string
              mount_options         = string
              client_install_runner = map(string)
              mount_runner          = map(string)
            }))
        defaultValue: []
      - name: native_batch_mounting
        description: Batch can mount some fs_type nativly using the 'volumes' block in the job file. If set to false, all mounting will happen through Cluster Toolkit startup scripts.
        varType: bool
        defaultValue: true
      - name: image
        description: "DEPRECATED: Google Cloud Batch compute node image. Ignored if `instance_template` is provided."
        varType: any
      - name: instance_image
        description: |
          Google Cloud Batch compute node image. Ignored if `instance_template` is provided.

          Expected Fields:
          name: The name of the image. Mutually exclusive with family.
          family: The image family to use. Mutually exclusive with name.
          project: The project where the image is hosted.
        varType: map(string)
        defaultValue:
          family: hpc-rocky-linux-8
          project: cloud-hpc-image-public
      - name: on_host_maintenance
        description: Describes maintenance behavior for the instance. If left blank this will default to `MIGRATE` except the use of GPUs requires it to be `TERMINATE`
        varType: string
      - name: submit
        description: When set to true, the generated job file will be submitted automatically to Google Cloud as part of terraform apply.
        varType: bool
        defaultValue: false
      - name: allow_automatic_updates
        description: |
          If false, disables automatic system package updates on the created instances.  This feature is
          only available on supported images (or images derived from them).  For more details, see
          https://cloud.google.com/compute/docs/instances/create-hpc-vm#disable_automatic_updates
        varType: bool
        defaultValue: true
    outputs:
      - name: gcloud_version
        description: The version of gcloud to be used.
      - name: instance_template
        description: Instance template used by the Batch job.
      - name: instructions
        description: Instructions for submitting the Batch job.
      - name: job_data
        description: All data associated with the defined job, typically provided as input to clout-batch-login-node.
      - name: network_storage
        description: An array of network attached storage mounts used by the Batch job.
      - name: startup_script
        description: Startup script run before Google Cloud Batch job starts.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.0"
      - source: hashicorp/local
        version: ">= 2.0.0"
      - source: hashicorp/null
        version: ~> 3.0
      - source: hashicorp/random
        version: ">= 3.0"
