apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/htcondor-install
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/htcondor-install
    actuationTool:
      flavor: Terraform
      version: ">= 0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: enable_docker
        description: Install and enable docker daemon alongside HTCondor
        varType: bool
        defaultValue: true
      - name: condor_version
        description: "Yum/DNF-compatible version string; leave unset to use latest 23.0 LTS release (examples: \"23.0.0\",\"23.*\"))"
        varType: string
        defaultValue: 23.*
      - name: http_proxy
        description: Set system default web (http and https) proxy for Windows HTCondor installation
        varType: string
        defaultValue: ""
      - name: python_windows_installer_url
        description: URL of Python installer for Windows
        varType: string
        defaultValue: https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
    outputs:
      - name: gcp_service_list
        description: Google Cloud APIs required by HTCondor
      - name: runners
        description: Runner to install HTCondor using startup-scripts
      - name: windows_startup_ps1
        description: Windows PowerShell script to install HTCondor
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
