apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/wait-for-startup
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/wait-for-startup
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: instance_name
        description: Name of the instance we are waiting for (can be null if 'instance_names' is not empty)
        varType: string
      - name: instance_names
        description: A list of instance names we are waiting for, in addition to the one mentioned in 'instance_name' (if any)
        varType: list(string)
        defaultValue: []
      - name: zone
        description: The GCP zone where the instance is running
        varType: string
        required: true
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: timeout
        description: Timeout in seconds
        varType: number
        defaultValue: 1200
      - name: gcloud_path_override
        description: Directory of the gcloud executable to be used during cleanup
        varType: string
        defaultValue: ""
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/null
        version: ~> 3.0
