apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/compute/schedmd-slurm-gcp-v-5-partition-dynamic
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic
    actuationTool:
      flavor: Terraform
      version: ">= 0.13.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: deployment_name
        description: Name of the deployment.
        varType: string
        required: true
      - name: slurm_cluster_name
        description: Cluster name, used for resource naming and slurm accounting. If not provided it will default to the first 8 characters of the deployment name (removing any invalid characters).
        varType: string
      - name: project_id
        description: Project in which the HPC deployment will be created.
        varType: string
        required: true
      - name: region
        description: The default region for Cloud resources.
        varType: string
        required: true
      - name: partition_name
        description: The name of the slurm partition.
        varType: string
        required: true
      - name: partition_conf
        description: |
          Slurm partition configuration as a map.
          See https://slurm.schedmd.com/slurm.conf.html#SECTION_PARTITION-CONFIGURATION
        varType: map(string)
        defaultValue: {}
      - name: is_default
        description: |
          Sets this partition as the default partition by updating the partition_conf.
          If "Default" is already set in partition_conf, this variable will have no effect.
        varType: bool
        defaultValue: false
      - name: subnetwork_self_link
        description: Subnet to deploy to.
        varType: string
      - name: subnetwork_project
        description: The project the subnetwork belongs to.
        varType: string
        defaultValue: ""
      - name: exclusive
        description: Exclusive job access to nodes.
        varType: bool
        defaultValue: true
      - name: partition_feature
        description: |
          Any nodes with this feature will automatically be put into this partition.

          NOTE: meant to be used for external dynamic nodes that register.
        varType: string
        required: true
    outputs:
      - name: partition
        description: Details of a slurm partition
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
