apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/pubsub/topic
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/pubsub/topic
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: deployment_name
        description: The name of the current deployment
        varType: string
        required: true
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: topic_id
        description: The name of the pubsub topic to be created
        varType: string
      - name: schema_id
        description: The name of the pubsub schema to be created
        varType: string
      - name: schema_json
        description: The JSON definition of the pubsub topic schema
        varType: string
        defaultValue: |
          {  
            "name" : "Avro",  
            "type" : "record", 
            "fields" : 
                [
                 {"name" : "ticker", "type" : "string"},
                 {"name" : "epoch_time", "type" : "int"},
                 {"name" : "iteration", "type" : "int"},
                 {"name" : "start_date", "type" : "string"},
                 {"name" : "end_date", "type" : "string"},
                 {
                     "name":"simulation_results",
                     "type":{
                         "type": "array",  
                         "items":{
                             "name":"Child",
                             "type":"record",
                             "fields":[
                                 {"name":"price", "type":"double"}
                             ]
                         }
                     }
                 }
                ]
           }
      - name: labels
        description: Labels to add to the instances. Key-value pairs.
        varType: map(string)
        required: true
    outputs:
      - name: topic_id
        description: Name of the topic that was created.
      - name: topic_schema
        description: Name of the topic schema that was created.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.42"
      - source: hashicorp/random
        version: ~> 3.0
