apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/file-system/cloud-storage-bucket
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/file-system/cloud-storage-bucket
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: ID of project in which GCS bucket will be created.
        varType: string
        required: true
      - name: deployment_name
        description: Name of the HPC deployment; used as part of name of the GCS bucket.
        varType: string
        required: true
      - name: region
        description: The region to deploy to
        varType: string
        required: true
      - name: labels
        description: Labels to add to the GCS bucket. Key-value pairs.
        varType: map(string)
        required: true
      - name: local_mount
        description: The mount point where the contents of the device may be accessed after mounting.
        varType: string
        defaultValue: /mnt
      - name: mount_options
        description: "Mount options to be put in fstab. Note: `implicit_dirs` makes it easier to work with objects added by other tools, but there is a performance impact. See: [more information](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#implicit-directories)"
        varType: string
        defaultValue: defaults,_netdev,implicit_dirs
      - name: name_prefix
        description: Name Prefix.
        varType: string
      - name: use_deployment_name_in_bucket_name
        description: If true, the deployment name will be included as part of the bucket name. This helps prevent naming clashes across multiple deployments.
        varType: bool
        defaultValue: true
      - name: random_suffix
        description: If true, a random id will be appended to the suffix of the bucket name.
        varType: bool
        defaultValue: false
      - name: force_destroy
        description: If true will destroy bucket with all objects stored within.
        varType: bool
        defaultValue: false
      - name: viewers
        description: A list of additional accounts that can read packages from this bucket
        varType: set(string)
        defaultValue: []
      - name: enable_hierarchical_namespace
        description: If true, enables hierarchical namespace for the bucket. This option must be configured during the initial creation of the bucket.
        varType: bool
        defaultValue: false
    outputs:
      - name: client_install_runner
        description: Runner that performs client installation needed to use gcs fuse.
      - name: gcs_bucket_name
        description: Bucket name.
      - name: gcs_bucket_path
        description: The gsutil bucket path with format of `gs://<bucket-name>`.
      - name: mount_runner
        description: Runner that mounts the cloud storage bucket with gcs fuse.
      - name: network_storage
        description: Describes a remote network storage to be mounted by fs-tab.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
      - source: hashicorp/google-beta
        version: ">= 6.9.0"
      - source: hashicorp/random
        version: ~> 3.0
