apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scripts/windows-startup-script
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scripts/windows-startup-script
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: install_nvidia_driver
        description: Install NVIDIA GPU drivers and the CUDA Toolkit using script specified by var.install_nvidia_driver_script
        varType: bool
        defaultValue: false
      - name: install_nvidia_driver_script
        description: Install script for NVIDIA drivers specified by http/https URL
        varType: string
        defaultValue: https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda_12.1.1_531.14_windows.exe
      - name: install_nvidia_driver_args
        description: Arguments to supply to NVIDIA driver install script
        varType: string
        defaultValue: /s /n
      - name: http_proxy
        description: Set http and https proxy for use by Invoke-WebRequest commands
        varType: string
        defaultValue: ""
      - name: http_proxy_set_environment
        description: Set system default environment variables http_proxy and https_proxy for all commands
        varType: bool
        defaultValue: false
      - name: no_proxy
        description: Environment variables no_proxy (only used if var.http_proxy_set_environment is enabled)
        varType: string
        defaultValue: 169.254.169.254,metadata,metadata.google.internal,.googleapis.com
    outputs:
      - name: windows_startup_ps1
        description: A string list of scripts selected by this module
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
