apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/network/vpc
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/network/vpc
    actuationTool:
      flavor: Terraform
      version: ">= 0.15.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: labels
        description: Labels to add to network resources that support labels. Key-value pairs of strings.
        varType: map(string)
        defaultValue: {}
      - name: network_name
        description: The name of the network to be created (if unsupplied, will default to "{deployment_name}-net")
        varType: string
      - name: subnetwork_name
        description: The name of the network to be created (if unsupplied, will default to "{deployment_name}-primary-subnet")
        varType: string
      - name: subnetwork_size
        description: "DEPRECATED: please see https://goo.gle/hpc-toolkit-vpc-deprecation for migration instructions"
        varType: number
      - name: default_primary_subnetwork_size
        description: The size, in CIDR bits, of the default primary subnetwork unless explicitly defined in var.subnetworks
        varType: number
        defaultValue: 15
      - name: region
        description: The default region for Cloud resources
        varType: string
        required: true
      - name: deployment_name
        description: The name of the current deployment
        varType: string
        required: true
      - name: network_address_range
        description: IP address range (CIDR) for global network
        varType: string
        defaultValue: 10.0.0.0/9
      - name: mtu
        description: "The network MTU (default: 8896). Recommended values: 0 (use Compute Engine default), 1460 (default outside HPC environments), 1500 (Internet default), or 8896 (for Jumbo packets). Allowed are all values in the range 1300 to 8896, inclusively."
        varType: number
        defaultValue: 8896
      - name: subnetworks
        description: |
          List of subnetworks to create within the VPC. If left empty, it will be
          replaced by a single, default subnetwork constructed from other parameters
          (e.g. var.region). In all cases, the first subnetwork in the list is identified
          by outputs as a "primary" subnetwork.

          subnet_name           (string, required, name of subnet)
          subnet_region         (string, required, region of subnet)
          subnet_ip             (string, mutually exclusive with new_bits, CIDR-formatted IP range for subnetwork)
          new_bits              (number, mutually exclusive with subnet_ip, CIDR bits used to calculate subnetwork range)
          subnet_private_access (bool, optional, Enable Private Access on subnetwork)
          subnet_flow_logs      (map(string), optional, Configure Flow Logs see terraform-google-network module)
          description           (string, optional, Description of Network)
          purpose               (string, optional, related to Load Balancing)
          role                  (string, optional, related to Load Balancing)
        varType: list(map(string))
        defaultValue: []
      - name: primary_subnetwork
        description: "DEPRECATED: please see https://goo.gle/hpc-toolkit-vpc-deprecation for migration instructions"
        varType: map(string)
      - name: additional_subnetworks
        description: "DEPRECATED: please see https://goo.gle/hpc-toolkit-vpc-deprecation for migration instructions"
        varType: list(map(string))
      - name: secondary_ranges
        description: |
          "Secondary ranges associated with the subnets.
          This will be deprecated in favour of secondary_ranges_list at a later date.
          Please migrate to using the same."
        varType: map(list(object({ range_name = string, ip_cidr_range = string })))
        defaultValue: {}
      - name: secondary_ranges_list
        description: List of secondary ranges associated with the subnets.
        varType: |-
          list(object({
              subnetwork_name = string,
              ranges = list(object({
                range_name    = string,
                ip_cidr_range = string
              }))
            }))
        defaultValue: []
      - name: network_routing_mode
        description: The network routing mode (default "GLOBAL")
        varType: string
        defaultValue: GLOBAL
      - name: network_description
        description: An optional description of this resource (changes will trigger resource destroy/create)
        varType: string
        defaultValue: ""
      - name: ips_per_nat
        description: The number of IP addresses to allocate for each regional Cloud NAT (set to 0 to disable NAT)
        varType: number
        defaultValue: 2
      - name: shared_vpc_host
        description: Makes this project a Shared VPC host if 'true' (default 'false')
        varType: bool
        defaultValue: false
      - name: delete_default_internet_gateway_routes
        description: If set, ensure that all routes within the network specified whose names begin with 'default-route' and with a next hop of 'default-internet-gateway' are deleted
        varType: bool
        defaultValue: false
      - name: enable_iap_ssh_ingress
        description: Enable a firewall rule to allow SSH access using IAP tunnels
        varType: bool
        defaultValue: true
      - name: enable_iap_rdp_ingress
        description: Enable a firewall rule to allow Windows Remote Desktop Protocol access using IAP tunnels
        varType: bool
        defaultValue: false
      - name: enable_iap_winrm_ingress
        description: Enable a firewall rule to allow Windows Remote Management (WinRM) access using IAP tunnels
        varType: bool
        defaultValue: false
      - name: enable_internal_traffic
        description: Enable a firewall rule to allow all internal TCP, UDP, and ICMP traffic within the network
        varType: bool
        defaultValue: true
      - name: enable_cloud_router
        description: Enable the creation of a Cloud Router for your VPC. For more information on Cloud Routers see https://cloud.google.com/network-connectivity/docs/router/concepts/overview
        varType: bool
        defaultValue: true
      - name: enable_cloud_nat
        description: Enable the creation of Cloud NATs.
        varType: bool
        defaultValue: true
      - name: extra_iap_ports
        description: A list of TCP ports for which to create firewall rules that enable IAP for TCP forwarding (use dedicated enable_iap variables for standard ports)
        varType: list(string)
        defaultValue: []
      - name: allowed_ssh_ip_ranges
        description: A list of CIDR IP ranges from which to allow ssh access
        varType: list(string)
        defaultValue: []
      - name: firewall_rules
        description: List of firewall rules
        varType: any
        defaultValue: []
      - name: firewall_log_config
        description: Firewall log configuration for Toolkit firewall rules (var.enable_iap_ssh_ingress and others)
        varType: string
        defaultValue: DISABLE_LOGGING
      - name: network_profile
        description: |
          A full or partial URL of the network profile to apply to this network.
          This field can be set only at resource creation time. For example, the
          following are valid URLs:
          - https://www.googleapis.com/compute/beta/projects/{projectId}/global/networkProfiles/{network_profile_name}
          - projects/{projectId}/global/networkProfiles/{network_profile_name}}
        varType: string
    outputs:
      - name: nat_ips
        description: External IPs of the Cloud NAT from which outbound internet traffic will arrive (empty list if no NAT is used)
      - name: network_id
        description: ID of the new VPC network
      - name: network_name
        description: Name of the new VPC network
      - name: network_self_link
        description: Self link of the new VPC network
      - name: subnetwork
        description: Primary subnetwork object
      - name: subnetwork_address
        description: IP address range of the primary subnetwork
      - name: subnetwork_name
        description: Name of the primary subnetwork
      - name: subnetwork_self_link
        description: Self link of the primary subnetwork
      - name: subnetworks
        description: Full list of subnetwork objects belonging to the new VPC network
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
