apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/file-system/filestore
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/file-system/filestore
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: ID of project in which Filestore instance will be created.
        varType: string
        required: true
      - name: deployment_name
        description: Name of the HPC deployment, used as name of the filestore instance if no name is specified.
        varType: string
        required: true
      - name: zone
        description: Location for Filestore instances below Enterprise tier.
        varType: string
        required: true
      - name: region
        description: Location for Filestore instances at Enterprise tier.
        varType: string
        required: true
      - name: network_id
        description: |
          The ID of the GCE VPC network to which the instance is connected given in the format:
          `projects/<project_id>/global/networks/<network_name>`"
        varType: string
        required: true
      - name: name
        description: The resource name of the instance.
        varType: string
      - name: filestore_share_name
        description: Name of the file system share on the instance.
        varType: string
        defaultValue: nfsshare
      - name: local_mount
        description: "Mountpoint for this filestore instance. Note: If set to the same as the `filestore_share_name`, it will trigger a known Slurm bug ([troubleshooting](../../../docs/slurm-troubleshooting.md))."
        varType: string
        defaultValue: /shared
      - name: size_gb
        description: Storage size of the filestore instance in GB.
        varType: number
        defaultValue: 1024
      - name: filestore_tier
        description: The service tier of the instance.
        varType: string
        defaultValue: BASIC_HDD
      - name: labels
        description: Labels to add to the filestore instance. Key-value pairs.
        varType: map(string)
        required: true
      - name: connect_mode
        description: Used to select mode - supported values DIRECT_PEERING and PRIVATE_SERVICE_ACCESS.
        varType: string
        defaultValue: DIRECT_PEERING
      - name: nfs_export_options
        description: Define NFS export options.
        varType: |-
          list(object({
              access_mode = optional(string)
              ip_ranges   = optional(list(string))
              squash_mode = optional(string)
            }))
        defaultValue: []
      - name: reserved_ip_range
        description: |
          Reserved IP range for Filestore instance. Users are encouraged to set to null
          for automatic selection. If supplied, it must be:

          CIDR format when var.connect_mode == "DIRECT_PEERING"
          Named IP Range when var.connect_mode == "PRIVATE_SERVICE_ACCESS"

          See Cloud documentation for more details:

          https://cloud.google.com/filestore/docs/creating-instances#configure_a_reserved_ip_address_range
        varType: string
      - name: mount_options
        description: NFS mount options to mount file system.
        varType: string
        defaultValue: defaults,_netdev
      - name: deletion_protection
        description: Configure Filestore instance deletion protection
        varType: |-
          object({
              enabled = optional(bool, false)
              reason  = optional(string)
            })
        defaultValue:
          enabled: false
    outputs:
      - name: capacity_gb
        description: File share capacity in GiB.
      - name: filestore_id
        description: An identifier for the resource with format `projects/{{project}}/locations/{{location}}/instances/{{name}}`
      - name: install_nfs_client
        description: Script for installing NFS client
      - name: install_nfs_client_runner
        description: Runner to install NFS client using the startup-script module
      - name: mount_runner
        description: |
          Runner to mount the file-system using an ansible playbook. The startup-script
          module will automatically handle installation of ansible.
          - id: example-startup-script
            source: modules/scripts/startup-script
            settings:
              runners:
              - $(your-fs-id.mount_runner)
          ...
      - name: network_storage
        description: Describes a filestore instance.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 6.4"
      - source: hashicorp/random
        version: ~> 3.0
