apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/network/private-service-access
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/network/private-service-access
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: address
        description: The IP address or beginning of the address range allocated for the private service access.
        varType: string
      - name: network_id
        description: |
          The ID of the GCE VPC network to configure private service Access.:
          `projects/<project_id>/global/networks/<network_name>`"
        varType: string
        required: true
      - name: labels
        description: Labels to add to supporting resources. Key-value pairs.
        varType: map(string)
        required: true
      - name: prefix_length
        description: The prefix length of the IP range allocated for the private service access.
        varType: number
        defaultValue: 16
      - name: project_id
        description: ID of project in which Private Service Access will be created.
        varType: string
        required: true
    outputs:
      - name: cidr_range
        description: CIDR range of the created google_compute_global_address
      - name: connect_mode
        description: |
          Services that use Private Service Access typically specify connect_mode
          "PRIVATE_SERVICE_ACCESS". This output value sets connect_mode and additionally
          blocks terraform actions until the VPC connection has been created.
      - name: private_vpc_connection_peering
        description: The name of the VPC Network peering connection that was created by the service provider.
      - name: reserved_ip_range
        description: Named IP range to be used by services connected with Private Service Access.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
      - source: hashicorp/google-beta
        version: ">= 3.83"
      - source: hashicorp/random
        version: ~> 3.0
