apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/modules/network/pre-existing-vpc
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/modules/network/pre-existing-vpc
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.14.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: network_name
        description: Name of the existing VPC network
        varType: string
        defaultValue: default
      - name: subnetwork_name
        description: Name of the pre-existing VPC subnetwork; defaults to var.network_name if set to null.
        varType: string
      - name: region
        description: Region in which to search for primary subnetwork
        varType: string
        required: true
    outputs:
      - name: network_id
        description: ID of the existing VPC network
      - name: network_name
        description: Name of the existing VPC network
      - name: network_self_link
        description: Self link of the existing VPC network
      - name: subnetwork
        description: Full subnetwork object in the primary region
      - name: subnetwork_address
        description: Subnetwork IP range in the primary region
      - name: subnetwork_name
        description: Name of the subnetwork in the primary region
      - name: subnetwork_self_link
        description: Subnetwork self-link in the primary region
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 3.83"
