apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-ai-on-gke-embedded/community/modules/scheduler/htcondor-pool-secrets
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-ai-on-gke
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-ai-on-gke
      sourceType: git
      dir: /modules/embedded/community/modules/scheduler/htcondor-pool-secrets
    version: 1.45.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3.0"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which HTCondor pool will be created
        varType: string
        required: true
      - name: deployment_name
        description: Cluster Toolkit deployment name. HTCondor cloud resource names will include this value.
        varType: string
        required: true
      - name: labels
        description: Labels to add to resources. List key, value pairs.
        varType: map(string)
        required: true
      - name: access_point_service_account_email
        description: HTCondor access point service account e-mail
        varType: string
        required: true
      - name: central_manager_service_account_email
        description: HTCondor access point service account e-mail
        varType: string
        required: true
      - name: execute_point_service_account_email
        description: HTCondor access point service account e-mail
        varType: string
        required: true
      - name: pool_password
        description: HTCondor Pool Password
        varType: string
      - name: trust_domain
        description: Trust domain for HTCondor pool (if not supplied, will be set based on project_id)
        varType: string
        defaultValue: ""
      - name: user_managed_replication
        description: Replication parameters that will be used for defined secrets
        varType: |-
          list(object({
              location     = string
              kms_key_name = optional(string)
            }))
        defaultValue: []
    outputs:
      - name: access_point_runner
        description: Toolkit Runner to download pool secrets to an HTCondor access point
      - name: central_manager_runner
        description: Toolkit Runner to download pool secrets to an HTCondor central manager
      - name: execute_point_runner
        description: Toolkit Runner to download pool secrets to an HTCondor execute point
      - name: pool_password_secret_id
        description: Google Cloud Secret Manager ID containing HTCondor Pool Password
      - name: windows_startup_ps1
        description: PowerShell script to download pool secrets to an HTCondor execute point
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.84"
      - source: hashicorp/random
        version: ">= 3.0"
